### ISSUE TITLE
Redo the `data/` folder to pages

### ISSUE THREAD

**Issue by elreydetoda** [JupiterBroadcasting/jupiterbroadcasting.com#110]
So, I meant to do this before with @StefanS-O's MVP repo, but didn't get to it before everything migrated (sorry :sweat:, life happened ([reference](https://matrix.to/#/!rDlEtonuSythLzmxQL:jupiterbroadcasting.com/$8noW3K5gYRKkcVykVswo8IDv5umzqFQw9z76rjqjWYA?via=matrix.org&via=jupiterbroadcasting.com&via=0x6b.dev))). Also, sorry for it being such a long issue, I just wanted to make it as comprehensive as possible. (Text only (at least for me) is hard to be as clear as possible without being overly verbose, for clarity sake)

### tl;dr:
the current way we're writing "people pages" (using raw json files to propagate everything), isn't as hugo _native_ as it could be. By having things more hugo native, it lends itself to doing things more efficiently and easily modifiable/usable with hugo native functions.

#### Current solution (from my understanding)

Repo is currently using raw json files for all people (hosts & guests).

#### Proposed solution

Instead of using machine readable (granted since it's not that long/large it's easily human readable for technical people) json, using Hugo's native [front matter](https://gohugo.io/content-management/front-matter/) + markdown under the `content/` folder is more what hugo expects (and I'm sure has more optimizations for building).

#### More info

The reason why (IMO) it's important to convert these from json to yaml, is because hugo has builtin functions to help handle pages more natively than it does with raw json.

For example, the [`where` function](https://gohugo.io/functions/where/), allows for easily being able to filter down arrays of Page objects. You can even get really complex with nesting `where` functions, and then you probably don't even have to use an if statement later. That's in comparison to having to load all the json files, and then looping over them all and having them each hit an if statement to see if they match a specific parameter.
This is an example of being able to filter the page objects (with `where`) before you actually start iterating over them: https://github.com/GWC-UNCC/Girls-Who-Code-at-UNCC/blob/6555ad7701ad0e281e2142d4ba518f72cd345b4a/layouts/partials/portfolio.html#L12

In the above example I was able to:
1. grab the portfolio pages (so we could highlight some of them on the main (home) page)
2. Then check if there are any pages whose date is newer than now (upcoming events)
3. Afterwards I was able to grab the first 3, so we could highlight only a few of them.

This allowed me to then easily iterate over them, like a normal list page would do but just inline on the homepage.

<br />

Another great example of using pages instead of json objects is whenever you want to work with pagination (i.e. what I was recommending on #92, instead of filtering (since pagination is native to hugo pages)).  If we use json objects, then we'll have to implement pagination by ourself. While on the other hand if they were pages pagination is builtin to hugo, and hugo has a native paginator (that you can override the colors for themeing).
For example, in a previous website I worked on, since all the posts were pages it was easy to implement pagination with about 3 lines of code:
1. Use this to indicate the pages you're ranging over need to be paginated: `{{ range (.Paginator 9).Pages }}`
2. Reference the content you want (like a normal page reference) and then close the range.
3. include this code block for the pagination functionality: `{{ template "_internal/pagination.html" . }}`

This will automatically handle slicing up all the page that need to be paginated, and placing them on the appropriate pages.
Here is the whole code block I used in my previous project:
https://github.com/Climate-Refugee-Stories/crs-website/blob/50d6f3f2ffcc6ac8d388063e7e159c14c477dbce/layouts/stories/list.html#L11-L17
Here is the live site's functionality: https://www.climaterefugeestories.com/stories/

<br />

Similarly to the last one, when doing list pages you'll get a bunch of native goodies with hugo and using page objects. One such example is that you can order pages with a special front matter field called `weight`. Hugo will look for this field when trying to list the individual pages and will automatically sort the pages based on that weight. It's sort of weird how they implement it, but 0/none = sorting by the next special frontmatter variable (A-Z or date) and then 1 > 2 > 3... So, everything after 1 is decreasing in priority, which makes sense for the average person, but programmers normally think of 0 first (or at least I do :sweat_smile: ).
Another example, all the people are listed under one folder here: https://github.com/Climate-Refugee-Stories/crs-website/tree/50d6f3f2ffcc6ac8d388063e7e159c14c477dbce/content/about.

Normally this was sorting by their name in alphabetical order, but we wanted to list the organizer (Tina) first. So, all we had to do was add the [weight of 1](https://github.com/Climate-Refugee-Stories/crs-website/blob/50d6f3f2ffcc6ac8d388063e7e159c14c477dbce/content/about/Tina-Shull.md?plain=1#L3) to her page, and she automatically is listed first now: https://www.climaterefugeestories.com/about/#our-team

<br />

Lastly, whenever there is a chance for implementing the CMS. If you're using pages for pulling people, at least with [NetlifyCMS](https://www.netlifycms.org), you can reference those pages and their front matter with relative ease via the [relation widget](https://www.netlifycms.org/docs/widgets/#relation).
That widget allows you to propagate information for the user to select from (i.e. hosts or guests when creating a new episode for a show). Here is a picture (using the netlify CMS docs as an example, since they've implemented it) of what it'd look like:

![image](https://user-images.githubusercontent.com/10230166/179444770-2a08108c-4f06-4d19-b787-3bc49070c757.png)

Here's how they did it:
1. this is their config for NetlifyCMS, and their intro config yaml: https://github.com/netlify/netlify-cms/blob/0c5efd19d6aa28e1e06a90c221ea0e8ac834ef33/website/static/admin/config.yml#L123-L128
2. They're using YAML [aliases & anchors](https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd) to keep their YAML [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself): https://github.com/netlify/netlify-cms/blob/0c5efd19d6aa28e1e06a90c221ea0e8ac834ef33/website/static/admin/config.yml#L16-L33
3. Inside that YAML anchor this is specifically the relation widget: https://github.com/netlify/netlify-cms/blob/0c5efd19d6aa28e1e06a90c221ea0e8ac834ef33/website/static/admin/config.yml#L23-L30

Which lets them propogate the dropdown based on their search terms, to select with the section name that the content should be placed under with their documentation (I was in the [overview section](https://www.netlifycms.org/docs/intro/)).

#### Technical implementation of scraping

Converting the scraper to use the new format shouldn't be that bad to implement either.  Since the yaml library already can handle reading with the `yaml.load_all()` function (according to [this](https://stackoverflow.com/a/34727830)), and the dumping function (similar to dumps for json in python) can write the same way: https://pyyaml.org/wiki/PyYAMLDocumentation#dumping-yaml (1st yaml doc = front matter & 2nd = MD content).

**Comment by kbondarev** [comment]
That is all very cool and interesting :)


> Also, sorry for it being such a long issue, I just wanted to make it as comprehensive as possible. (Text only (at least for me) is hard to be as clear as possible without being overly verbose, for clarity sake)

It's fine, I always try very hard to use least amount of words in text. Sometimes it doesn't work.

---

I sort of understand that having the people defined under `/content` (and maybe even sponsors) will result in more advantage. But does the front-matter part has to be in YAML, my understanding was that Hugo doesn't care whether it's YAML, JSON, or TOML.

It is very trivial to move from one format to another with the scraper. It just feels wrong to me to override thousands of files again lol.

I installed the front-matter plugin for VS and noticed that for it to work it needs to have the JSON surrounded with `---` or `+++`. This is annoying because it's not what it said [here](https://gohugo.io/content-management/front-matter/). So the episode files would probably need to be modified at least once again no matter what :fearful:

**Comment by elreydetoda** [comment]
> I sort of understand that having the people defined under `/content` (and maybe even sponsors) will result in more advantage. But does the front-matter part has to be in YAML, my understanding was that Hugo doesn't care whether it's YAML, JSON, or TOML.

Ya, I guess you're right it technically could be any of those 3... 🤔

> It is very trivial to move from one format to another with the scraper. It just feels wrong to me to override thousands of files again lol.

Ya, it definitely does feel weird in my head as well 😅 We will at least have to move all the files and swap a .md extension for the .json one. So, that's why I was figuring we could just make things more easily human readable as well. I guess it doesn't have to be though.

> I installed the front-matter plugin for VS and noticed that for it to work it needs to have the JSON surrounded with `---` or `+++`. This is annoying because it's not what it said [here](https://gohugo.io/content-management/front-matter/). So the episode files would probably need to be modified at least once again no matter what :fearful: 

Ya, probably... 😞

I could try and do an MVP of what that'd look like with the scraper if you want? I kind of wanted to dig into the code more myself anyway 😁 (I love understanding other people's python code and how they approach problems 🙃).

**Comment by kbondarev** [comment]
The scraper code is a little bit messy :see_no_evil:. Most of the work was done one manic night when I grabbed the original code from the self-hosted show-notes repo, and started playing around with it. There's a lot there that could be done "cleaner".

The one good thing I did I use Pydantic a little. Those data objects for Person and Episode could be easily dumped as YAML instead if that's what we desire. Using [this extension to Pydantic](https://pypi.org/project/pydantic-yaml/)

---

Said all that maybe wait for feeedback from @StefanS-O before you start spending time on this. Stefan started a lot of work on this project and might have some very specific reason why some things where done the way they're done.

**Comment by gerbrent** [comment]
All the above is fascinating, nice insights!

> Said all that maybe wait for feeedback from @StefanS-O

I agree completely there - don't spend time till we decide this is a great trajectory.

**Comment by StefanS-O** [comment]
We should do this, because it would also make pagination work on host /gues sites.
Hugo can't paginate data structures.

**Comment by elreydetoda** [comment]
Alright, sounds good. I'll try and start working on this as soon as I can.

🙂

Thank you @StefanS-O , @gerbrent , and @kbondarev for taking the time to read this and consider the options 🙂

**Comment by elreydetoda** [comment]
Alright, so an update on this...I've just made the PR this morning for the scraper to get the functionality to handle placing all the people & sponsors in the `content/` folder instead of the `data/` folder. @kbondarev messaged me letting me know he'll review it when he gets a chance, so once we figure out if everything will workout then we should be good from that perspective.

https://github.com/JupiterBroadcasting/show-scraper/pull/19

Still have to implement the logic on this repo before we can merge anything on the scraper repo, because it'll break the update logic from the GH action if we don't merge in on this side first.

Honestly, once I finish implementing the logic here we'll probably need to have some one merge locally and then run the scrapper locally as well.  Then they can commit all the new content + my newly merged logic to help prevent the site breaking in production :sweat_smile: 

I can do this as well, but didn't know if someone else wanted to so another set of eyes can review all the changes locally before it's merged/pushed to the main branch.

**Comment by gerbrent** [comment]
This feels like both a @kbondarev and @StefanS-O set of eyes/thoughtfulness would be appreciated....

**Comment by kbondarev** [comment]
Actually closed by #252 (via #261)

Reopened accidentally by referencing in other issue
