### ISSUE TITLE
vjs.zencdn.net blocked by pihole

### ISSUE THREAD

**Issue by elreydetoda** [JupiterBroadcasting/jupiterbroadcasting.com#116]
Just wanted to give a heads up that I use a [pi-hole](https://pi-hole.net) at home, and I'm pretty sure I use [this list of block lists](https://v.firebog.net/hosts/lists.php) (the Non-crossed lists group), and that domain (vjs.zencdn.net) was getting blocked (from [here](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/551e71a20d01b5fa9c8b87fd7d66dbc7613c116e/themes/jb/layouts/episode/single.html#L2)).

![image](https://user-images.githubusercontent.com/10230166/179650942-81cbcc1c-802c-4a5f-b660-9a24ed64d2e2.png)

So, it might be worth considering just pulling that file into the project and serving it from JB's domain instead of the other domain. That way it won't get blocked, I'm just whitelisting it on my DNS for now but something to think about for other people.

**Comment by gerbrent** [comment]
What even is this file used for?

I can see from the git blame that it's been there a [long time](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blame/551e71a20d01b5fa9c8b87fd7d66dbc7613c116e/themes/jb/layouts/episode/single.html#L2) (relatively) and I wonder if it's a relic from the previous embedded web player?

Can anyone clarify if this is even needed? Would avoid needing #445 altogether if it wasn't required.

**Comment by CGBassPlayer** [comment]
So just poking around, I can see that there is a commented out line on the episode page calling a video player for the episode page (I assume leftover from the MVP)

```html
<!-- {{ partial "episode/videoplayer.html" . }} -->
```
```html
<video
    id="my-video"
    class="video-js vjs-fluid"
    controls
    preload="auto"
    width="640"
    height="264"
    poster="{{.Params.header_image}}"
    data-setup="{}"
  >
  {{.Params.video_file}}
    <source src="{{.Params.video_file}}" type="video/mp4" />
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a
      web browser that
      <a href="https://videojs.com/html5-video-support/" target="_blank"
        >supports HTML5 video</a
      >
    </p>
  </video>
```
Given that we do not want to have video on the site anymore. I think it would be safe to remove the `video-js` and video player partial from the site entirely. Unless there is someone can give any reason why we should keep this around.

I also went through the html handling the live and it is not using `video-js` either, that is just rendering an `iframe` with the PeerTube API.
