### ISSUE TITLE
Consider Ghost CMS

### ISSUE THREAD

**Issue by JR-git-hub** [JupiterBroadcasting/jupiterbroadcasting.com#12]
Ghost CMS was "made for content creators by content creators".  It can be self hosted or SaaS. 

They attempt to help creators monitize their work and perhaps have some features JB would utilize well.  They probably don't support SATs but maybe JB can make that case and perhaps Ghost would be interested in a partnership.

Ghost.org

**Comment by gerbrent** [comment]
Thanks!

Ghost is actively discussed here, along w the other options: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/discussions/8
