### ISSUE TITLE
jblive.tv - embeded jupiter.tube

### ISSUE THREAD

**Issue by reesericci** [JupiterBroadcasting/jupiterbroadcasting.com#122]
JB has been really pushing the use of JupiterTube and with JB switching away from Wordpress, JupiterTube should become the live stream embed on the new website instead of the ol' jblive.tv RTMP server.

**Comment by reesericci** [comment]
JBot could (and arguably should) take the role of starting up the stream. That way the endpoint would always know where the stream is located to embed on the site.

**Comment by gerbrent** [comment]
To ask so much of JBot is to rely on the unknown and fragile... she is unmaintained and frankly quite old. BUT... what you are suggesting is certainly a welcomed improvement. Anything we can do to make some of our Live processes automated AND super reliable are helpful...

But I would suggest you don't work on that pipeline 'till we can get some buy-in from the likes of @noblepayne and @ChrisLAS, and likely till after the JB 1.0 Milestone too..

**Comment by kd2flz** [comment]
I don't know a lot about RSS, but it is possible to generate a RSS feed from PeerTube. Not sure if the live stream would show up in the RSS feed though.

**Comment by reesericci** [comment]
JBot needs to be rewritten, so this more is about the successor of JBot @gerbrent

**Comment by elreydetoda** [comment]
Is JBot something that's open source, or internally hosted by JB? I haven't written a bot before for much, so I'd be curious to see the code 😁

**Comment by gerbrent** [comment]
> Is JBot something that's open source, or internally hosted by JB? I haven't written a bot before for much, so I'd be curious to see the code grin

Here's a gift for you:

* I forked the previous source of JBot for you/everyone (source detailed on the footer of https://jbtitles.com/):

https://github.com/JupiterBroadcasting/jbot-showbot

**Comment by gerbrent** [comment]
That being said, we're really looking to migrate to GammaBot - our JBot Matrix replacement thanks to Gamma/Matrix.

That can be found [here](https://github.com/xPMo/hemppa-bot/) for now, but will be migrating to JB Repos very soon..

@xPMo = Gamma

**Comment by gerbrent** [comment]
This particular issues is a great example of an ideal 2.0 Milestone enhancement. Marking as so.

**Comment by gerbrent** [comment]
Hey all!

Chris, Wes and I did some (sloppy) experimentation on the Live page and embedded a peertube stream. 
I was hoping someone could go in and clean up my (sloppy) work in making the peertube embed our preferred embed.

#### What I did
I commented out the twitch iframe in the twitch partial and pasted the peertube iframe instead. 

#### How it should be instead
....better ; )


code: 
themes/jb/layouts/partials/live/twitch.html
https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/7d889afea2ddaa1f5274ae478a0ff45e093d3782/themes/jb/layouts/partials/live/twitch.html

not sure how many best practices rules I broke with the above, but if someone would be kind enough to *properly* implement the peertube embed, that would be splendid.

**Comment by iarwain-forn** [comment]
🚧 I cleaned up the twitch references in the HTML and file name over [here](https://github.com/iarwain-forn/jupiterbroadcasting.com/commit/b8a013861a8d6dc41ef15e837adf12bf177daf03) ([diff](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/compare/main...iarwain-forn:jupiterbroadcasting.com:iarwin/issue122)).

I think I should be able to make a small javascript module that returns either the current live video or the most recent video if nothing is live. Would that be something y'all were interested in? That way the videos can stay easily archived, in the long term the code could move to a CloudFlare Worker or something similar so the site and bot could link to a permanently redirecting URL.

**Comment by iarwain-forn** [comment]
And 🚧 [here's](https://github.com/iarwain-forn/jupiterbroadcasting.com/commit/01177773cdca15b85538285e28e45cdb537c52e2) the MVP for grabbing the current or most recent show every time. Let me know if I should move forward with integrating the two parts or if you want a more static way to do this.

**Comment by kbondarev** [comment]
@iarwain-forn It looks like a good solution! :rocket: 
Could you please make a PR for those changes and tag this issue in the comment there? It aligns better with the current workflow. A PR helps @gerbrent  &  @StefanS-O  to notice new incoming changes that should be reviewed.

If the work isn't ready to be merged yet, and you just want to show a preview of your work and discuss the direction you're taking (as it seems to be in this case), then you could make the PR as a "Draft".

**Comment by kbondarev** [comment]
@iarwain-forn I looked a little more into this, and I'm not sure if that JavaScript code you wrote is even required. It seems to me that the PeerTube URL @gerbrent put in that iframe is a special one, and it would also be the most recent stream whether it's live or archived. @gerbrent can you confirm?

**Comment by reclaimingmytime** [comment]
@kbondarev
> It seems to me that the PeerTube URL @gerbrent put in that iframe is a special one, and it would always be pointing to the most recent stream - whether it's a live one or not.

It doesn't seem to update dynamically. Chris changed the PeerTube iframe URL yesterday for Coder in commit https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/commit/4a39857255570f44dad367a563225a1880423ec5 .

**Comment by ChrisLAS** [comment]
We can do it either way. 

But there are a couple of advantages to embedding an episode-specific PeerTube stream.

1. When we create a new stream post for each show, we get a shareable URL that will always link back to that stream. That's useful for folks who see the message about a stream after the fact. 
2. We can leave it embedded on the live page until the next live stream. Making the previous stream easily accessible.
3. We can set per-stream teaser images for the video thumbnail. IE give hints for the upcoming episode's contents.

The biggest downside IMHO is we gotta swap out the embed each time. Not a huge overhead, but a manual step ATM.

**Comment by gerbrent** [comment]
> The biggest downside IMHO is we gotta swap out the embed each time. Not a huge overhead, but a manual step ATM.

Some ideas around workflow or automation to help Chris in this task would be amazing. On the current WP site, this is the page he modifies the most, something like 1000 times since 2009...

There might even be a slick way to swap out the embeds, or automate it... 
@noblepayne offers a few spitballs  to get ideas started:

> Peertube does have an API, and since the player is JS anyway, one route might be having some JS that calls the Jupiter.Tube API to find if there is currently a live show and then embed that. Bit much though, so hopefully our talented team has some simpler ideas.

> A reverse approach might be a tool/[gamma bot](https://github.com/JupiterBroadcasting/gammabot)/something that helps in starting the stream (or is watching for new streams) and then pushes the edit to the site automatically. maybe even #41 is related..

**Comment by kbondarev** [comment]
> A reverse approach might be a tool/[gamma bot](https://github.com/JupiterBroadcasting/gammabot)/something that helps in starting the stream (or is watching for new streams) and then pushes the edit to the site automatically. maybe even https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/41 is related..

I like this :point_up:. 
Here's a suggestion of how it might work:

#### Option 1:
- new live stream is started on PeerTube
- start show command is issued in Matrix
- gammabot:
  - queries the PeerTube API for the URL for the current live stream
  - checks out the repo (maybe with the git `--depth=1` option)
  - updates the url in the file and commits

_For this to work the system that runs gammabot will need to have an SSH key that has permissions to commit to github_

#### Option 2:
Same as above but instead of gammabot doing the PeerTube API querying, there would be a GH action that would do it. And gammabot will trigger that action via GitHub API.

_GitHub SSH key not required for this. But instead an GitHub PAC (personal access token)_

--- 

I think I like option 2 better since it is a little more modular. If for instance Gammabot is dead, Chris could just go into GitHub Actions and press the button to trigger that workflow manually.

**Comment by reesericci** [comment]
The current live show shouldn't be kept in git, it is information that doesn't need to be version-controlled and is changing frequently. It's not fast, and git isn't designed for the usecase. It should be kept instead in a database like redis, and put behind an endpoint like discussed in #41

**Comment by iarwain-forn** [comment]
@gerbrent I think #254 being merged can close out this issue.

**Comment by reesericci** [comment]
I had no idea that you could retrieve the latest stream from the API (even though i've looked for exactly that in the docs). Could this work for putting an alert on the page as described in #41 ?

**Comment by reesericci** [comment]
and #34
