### ISSUE TITLE
RSS feed references - point to Fireside feeds

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#126]
in response to decisions in #108

links to show feeds throughout the site should link to Fireside-appropriate feeds, i.e. the current rss feeds in use via Fireside will persist through the JB.com 1.0 Milestone.

@StefanS-O 's work on custom hugo-generated RSS feeds should be captured somehow for future use if possible.

**Comment by kbondarev** [comment]
I think simplest way is maybe to add some NGINX redirect rules. Something like this:

```
location  ~ ^show/linux-unplugged/rss$ {
    return 301  https://linuxunplugged.com/rss;
}
```

**Comment by elreydetoda** [comment]
> > work on custom hugo-generated RSS feeds should be captured somehow for future use if possible.
> 
> @elreydetoda Can you discuss a little about how this was thought of and presumably accomplished or not?

So, I left all the code and files that @StefanS-O had created before, and just commented it out. For example:
- [this](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/2607d878bc97fa7ee98727bd124dc829a62ea093/themes/jb/layouts/section/list.rss.xml) is the file which Stefan used to generate all the feed
  - I just am telling hugo to not do that type of build anymore, with [this line](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/130/files#diff-28043ff911f28a5cb5742f7638363546311225a63eabc365af5356c70d4deb77R205) and telling hugo to only build HTML [here](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/130/files#diff-28043ff911f28a5cb5742f7638363546311225a63eabc365af5356c70d4deb77R206) (not RSS).
- Then I commented all the code out which referenced the generated RSS file [here](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/130/files#diff-e86c9d1d430e385af1e6c02d51cc7ce84904e8782352c08fe7c7d0e5e85ba55aR51-R54)

So, I addressed it by just commenting everything out. Thank you for asking for more info about it, I love explaining things :grin: and hope it helped. Please let me know if there are any other questions you have about it :slightly_smiling_face:

**Comment by elreydetoda** [comment]
> I think simplest way is maybe to add some NGINX redirect rules. Something like this:
> 
> ```
> location  ~ ^show/linux-unplugged/rss$ {
>     return 301  https://linuxunplugged.com/rss;
> }
> ```

So, I think that could probably work for if someone does `/rss` on a show (which would be really cool :grin: IMO), but this issue is for the all shows feed (from my understanding and looking at Stefan's RSS implementation) which is hosted on JB.com now.
