### ISSUE TITLE
Not loading all Bulma stuff?

### ISSUE THREAD

**Issue by elreydetoda** [JupiterBroadcasting/jupiterbroadcasting.com#128]
I've never used bulma before, but I saw the convention (similar to bootstrap) about a [12 column system](https://bulma.io/documentation/columns/sizes/#12-columns-system). So, I went to specify `is-10` but it doesn't seem like that's been loaded :thinking: 

![image](https://user-images.githubusercontent.com/10230166/179894218-7fbabb78-dc4a-4c4d-85d9-09511496c998.png)

I know I had to enable the breadcrumbs before, but I've got no idea where to go to uncomment that (and too many things match with 10  :sweat_smile: 

Any ideas what's going on?

**Comment by kbondarev** [comment]
I noticed it as well... My guess is that, @StefanS-O wanted to not include things that aren't used. 
@StefanS-O can you confirm? Maybe we should add everything, I don't think the whole lib is that heavy. Even if some componets/elements aren't in use - it wouldn't affect things much.

**Comment by StefanS-O** [comment]
I really don't know why i did remove those, readded everything!
