### ISSUE TITLE
episode page - remove video player, prioritize embedded player

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#131]
The video player embed is an artifact of the old WP site needing this workaround to embed media. 

Since we have wonderful embedded player choices, the video player is no longer needed and we should prioritize the embedded player.

Reasoning:
* the embedded player presents many more features - chapters, speed changes, etc. 
* the video here is not the highlight of the episodes ATM, audio production is our main focus. Lets let it shine!
* visually simplifies the episode pages
* while we DO have video feeds now on Jupiter.Tube, these are NOT the polished end product our audio editors work so hard to create.

**Comment by kbondarev** [comment]
Closed by #133
