### ISSUE TITLE
Show page - Direct Downloads - links are to current page, not mp3/Youtube, etc

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#138]
![image](https://user-images.githubusercontent.com/7018928/180264598-afd54408-adba-4555-a647-12a8a2998f6e.png)

The links to various "Direct Downloads" point to the current page/episode when they should point to their respective downloads.

Current code being rendered:
`Direct Download: [MP3](https://jupiterbroadcasting.net/show/linux-unplugged/465/) | [Video](https://jupiterbroadcasting.net/show/linux-unplugged/465/) | [YouTube](https://jupiterbroadcasting.net/show/linux-unplugged/465/)`

**Comment by kbondarev** [comment]
Not related to the scraper.

The template just has empty links: `<a src="">`
It's a quick fix - I'll fix this later today, unless someone beats me to it :rocket:

**Comment by kbondarev** [comment]
To be clear: I unassigned myself to open this for someone else to do (I don't have much time today). But I'll probably fix it tomorrow if it's not done by them.

The solution:
- Use the parameters in the episode markdown file to set the `src` attributes of the link
- There are more than just these 3 options (there's also ogg file sometimes and different video files)
- :exclamation: All of these params are **optional**, meaning they could be unset (null or empty string). Need to check for that and don't display the link in that case

**Comment by gerbrent** [comment]
> Not related to the scraper.

that tag was bait 🎣 to get your thoughts in here ; ) (although in retrospect, knowing your dedication, probably not needed...)

**Comment by aaronrea** [comment]
Howdy, this looks like something I could tackle. Probably easiest to create a partial for this section? If i understand how ya'll are passing the episode data around, I should just be able reference `.Params.podcast_alt_file`, etc, if not null.

**Comment by gerbrent** [comment]
@aaronrea - happy to assign you to this - thanks!!

I'll let someone else answer your Q above - @kbondarev ? @StefanS-O ?
