### ISSUE TITLE
https://www.jupiterbroadcasting.net = Coder Radio MVP

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#142]
Just a quick observation:

browsing to https://www.jupiterbroadcasting.net/ instead of https://jupiterbroadcasting.net/ leads to the Coder MVP (not the current JB.net website)

note the "www"

**Comment by StefanS-O** [comment]
I forgot to add www.jupiterbroadcasting.net to nginx, fixed it
