### ISSUE TITLE
Hosts/Guests Profile images not clickable...sometimes.

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#147]
Profile images for all Hosts, Guests throughout the site are not clickable/links, only their Name on the cards are clickable/links.

This applies in various locations:
* [ ] [JB Hosts page](https://jupiterbroadcasting.net/hosts/)
* [ ] Episode pages - e.g. [Coder475](https://jupiterbroadcasting.net/show/coder-radio/475/), [LUP467](https://jupiterbroadcasting.net/show/linux-unplugged/467/), et. al

This behavior *IS* as intended on:
* [x] [JB Guests page](https://jupiterbroadcasting.net/guests/)

**Comment by CGBassPlayer** [comment]
I can take care of this. 

I do propose that the entire card is the clickable link for the Host and Guest pages as well as the Host cards on the episode pages. Reason being that then the user doesn't need to "find" the link in the card, they can just click the card as a whole to get to where they want to go.

**Comment by gerbrent** [comment]
@CGBassPlayer you more accurately described my desired behaviour, since... somehow I left that out of my initial ticket description. Nicely done and exactly the intended behaviour!
