### ISSUE TITLE
Show descriptions - incorrect, outdated, need updating

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#153]
Some of the show descriptions need updating.
See them here: https://jupiterbroadcasting.net/show/

Reference descriptions should from the shows' current individual websites i.e. Fireside pages:
(also todo list:) 

* [ ] [LINUX Unplugged](https://linuxunplugged.com/)
* [ ] [Self-Hosted](https://selfhosted.show/)
* [ ] [Coder Radio](https://coder.show/)
* [ ] [Linux Action News](https://linuxactionnews.com/)
* [ ] [Jupiter Extras](https://extras.show/)
* [ ] [Office Hours](https://www.officehours.hair/)
  
Definitely in need of work, and/or outdated: 
* LAN - lists Joe as host
* Office Hours - stand-in description

All shows should be verified.
Thanks!!!

**Comment by harriseldon** [comment]
I would like to work on this. I forked the repository and made changes to the _index.md file for Linux Action News and Office Hours. I will check the rest then create my pull request. I also joined the Matrix chat and I will ask other questions there.

**Comment by harriseldon** [comment]
Created pull request https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/166
