### ISSUE TITLE
Home Page logo - starry-sky background not needed........

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#155]
The galactic background to the Home Page's JB logo doesn't need to exist. 
If anything, it makes the JB Logo and subtext difficult to read. 

Would be happy to see some mockups of alternatives. Simpler is better. Possibly just.... no background would suffice.

![image](https://user-images.githubusercontent.com/7018928/180341708-90253854-131a-4b9b-b868-9c42caf46b11.png)

**Comment by StefanS-O** [comment]
I have removed the background image
