### ISSUE TITLE
"Jupiter Broadcasting" Host - useful?, broken link, which episodes?

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#157]
There is a host listing for "Jupiter Broadcasting" in [Hosts[(https://jupiterbroadcasting.net/hosts/) however it is unclear why this is useful, which shows link to this as a host, and why it's profile page is broken.

It's profile links here: https://jupiterbroadcasting.net/hosts/default - which is a 404

Could this have been a placeholder during MVP stages of the site?

We should:
* [ ] identify any episodes that link to it
* [ ] investigate whether this is a useful profile

If useful, we should:
* [ ] fix the 404
* [ ] adjust the design to fit well with other profiles - i.e. square cropped "profile photo"

**Comment by CGBassPlayer** [comment]
Just wanted to throw in the "Friends of Jupiter Broadcasting" Host that is a host for an old out takes clip in [Jupiter Extras  9](https://jupiterbroadcasting.net/show/jupiter-extras/9/). My guess is it would need a similar decision of what to do with it

**Comment by gerbrent** [comment]
this seems to have been fixed magically.
