### ISSUE TITLE
"Support Show" button design on Episode pages - needs change

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#159]
The bright green colour of the "Support $SHOW" button on Episode pages does not match any of the rest of the site's colour scheme, and frankly I find a little hard to read the white-on-green text (could be my need for new glasses...)

Open to exploration of different options.

Also opening a conversation about the placement of said button:
Would placing the button in the hosts/sponsors section, i.e. below the embedded player, be a more natural fit?

# 
![image](https://user-images.githubusercontent.com/7018928/180492674-67f53483-086d-48fd-8ee3-d6e4ba7693cd.png)

**Comment by trev-dev** [comment]
You could use some CSS and convert the image into a button that you may click to "support the show." Or, simpler yet, Just make it a fairly obvious clickable link somewhere on the left-hand side either below the title, date or synopsis.

I know you want your CTA to be pretty loud, but I agree, giant neon green is a bit too loud.

**Comment by gerbrent** [comment]
I would be totally open to other options - it's literally the only thing on the entire site that's green - feels totally out of place to me. It also tends to clash with most of our show artwork...

You? What do you think?

Perhaps beginning to experiment w the blue in the Podverse player timeline....

**Comment by reesericci** [comment]
I think there should be a section right above sponsors with two cards: the membership and jupiter party

**Comment by kbondarev** [comment]
It is my fault :see_no_evil: 
I made the `success` color (which is used for the button) this neon green (JB randing color from choose-linux) and that changed it like it.

**Comment by Lord0fBytes** [comment]
Tisk tisk 😋. I am changing the color of the button to that blue color from the podverse and will use a custom bulma sass file for it to help with the branding of all the buttons.

**Comment by kbondarev** [comment]
@Lord0fBytes I already modified it, see #201

**Comment by gerbrent** [comment]
@kiro, that feels SOOOOO much better! Nicely done

![image](https://user-images.githubusercontent.com/7018928/182409201-55f3a942-918e-4bb9-927b-71e83660d07d.png)
