### ISSUE TITLE
"Support Show" button on Episode pages - links to wrong membership

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#160]
An audit of the "Support $SHOW" button on Episode pages reveals some incorrect linking to membership pages.

* [ ] [Office Hours](https://jupiterbroadcasting.net/show/office-hours/8/): `Support Office Hours` ->  [Coder QA Membership](https://jupitersignal.memberful.com/checkout?plan=53334)
   * [ ] should be `Support Office Hours` -> [Network Membership](https://jupitersignal.memberful.com/checkout?plan=74364), or https://jupiterbroadcasting.net/membership/
   
#### Others to fix:
* [x] Coder Radio -> Coder QA
* [ ] Linux Unplugged -> [LINUX Unplugged Core Contributor](https://jupitersignal.memberful.com/checkout?plan=52946)
* [ ] Self-Hosted -> [Self-Hosted SRE](https://jupitersignal.memberful.com/checkout?plan=53744)
* [ ] LAN -> [Network Membership](https://jupitersignal.memberful.com/checkout?plan=74364), or https://jupiterbroadcasting.net/membership/
* [ ] Extras -> [Network Membership](https://jupitersignal.memberful.com/checkout?plan=74364), or https://jupiterbroadcasting.net/membership/

Also considering just linking all of these to the Membership page. Simpler, and offers all options to consider.

**Comment by gerbrent** [comment]
Assigning myself, since.... some JB decisions to be made, and simple to implement.

**Comment by elreydetoda** [comment]
Just a note, all of these should be editable via the `_index.md` files under each of the shows. For example this would be where you could change Office Hour's support link:

https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/b716aa253cb6d82990f9f1ee515bf299e8008e16/content/show/office-hours/_index.md?plain=1#L15

**Comment by gerbrent** [comment]
opening this up for someone else to take, since.... I'm the block here.

I'm recommending that we link everything to `./membership`, since it'll give an overview of network membership options, which is a good thing.

**Comment by reclaimingmytime** [comment]
> I'm recommending that we link everything to ./membership

I can contribute this change.
