### ISSUE TITLE
New color for links

### ISSUE THREAD

**Issue by CGBassPlayer** [JupiterBroadcasting/jupiterbroadcasting.com#164]
Brought up in issue #148, the blue color for links can feel distracting where there a good amount on a page. I am thinking we could copy the color scheme that is used in the footer section (light grey / white) for a more stealthy look. Any thoughts on this?

**Comment by reesericci** [comment]
I personally think the blue isn't distracting and it's very clear to the reader that there's a link there. The link color also falls in line with the JB brand guidelines.

--reese

**Comment by gerbrent** [comment]
Here's a side-by-side of what I mean by legibility:

On the left, this site. On the right: GitHub.
Very similar colour schemes, yet to my eye the right blue link colour is far more vibrant, contrasty, and thus more legible.

![image](https://user-images.githubusercontent.com/7018928/181821029-2bb4c919-052a-4317-8716-fbe728bfc1cf.png)

**Comment by gerbrent** [comment]
another sample.
left = hugo, right = fireside

![image](https://user-images.githubusercontent.com/7018928/181825700-cfb4e531-806b-4972-b3c5-022a0c8fc907.png)

**Comment by CGBassPlayer** [comment]
It almost seems like the links on the Hugo Site require more effort to read because the grey background has way more blue in it. I am not exactly sure how to describe it.

**Comment by kbondarev** [comment]
How about this (I basically switched the color of the link and the color of the link-on-hover):

![image](https://user-images.githubusercontent.com/7744333/181933372-43bbecd4-12ef-411e-88f9-ef1fb3ad7c42.png)
