### ISSUE TITLE
EXTRAS, Office Hours Show Page - missing buttons/icons/links

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#185]
The following buttons/icons/links are missing from Show pages compared to other Shows:

### [EXTRAS](https://jupiterbroadcasting.net/show/jupiter-extras/) 

* [ ] "show notes" link > https://extras.show/
* [ ] "contact" link > https://extras.show/contact

### [Office Hours](https://www.officehours.hair/)
* [ ] "show notes" link > https://www.officehours.hair/
* [ ] "contact" link > https://www.officehours.hair/contact (doesn't exist, see #184)

**Comment by aaronrea** [comment]
I can knock this out tonight
