### ISSUE TITLE
Make shorthand for Shows in hugo directories consistent w JB internal shorthands

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#19]
naming convention for Shows should be consistent, either:

### JB shorthand: 
* coder
* extras
* lan or LAN
* lup or LUP
* office
* ssh or SSH

### lower-kebab-case: 
(likely the better choice)
* coder-radio
* extras
* linux-action-news
* linux-unplugged
* office-hours
* self-hosted

### currently - a mix of naming conventions
/content/coderradio
/content/extras
../linux-action-news
../linuxun
../officehours
../selfhosted

**Comment by gerbrent** [comment]
Realizing now that accurately, Extras is actually/officially "Jupiter Extras", thus for kebab consistency:

* add todo to change "extras" slug to "jupiter-extras"

(encountered as I was using a ref in some content/text to the show following our naming convention, and hugo threw an error.)

**Comment by StefanS-O** [comment]
@kbondarev would you als rename the existing folder in the Hugo repo in that step?

**Comment by kbondarev** [comment]
@StefanS-O yep, I plan to rename the Hugo folder and anywhere it's referenced, as well as, the show-scraper stuff.

I'll make 2 PR in both repos (scraper and huge site) - I think they should be merged at the same time. I link them here in this issue when both ready to merge.

**Comment by kbondarev** [comment]
So these two should be merged at the same time into their respective repos:

https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/51

https://github.com/JupiterBroadcasting/show-scraper/pull/7



(I know that I have permissions to merge, but I'll leave that to @StefanS-O as the original maintainer of this repo :smile: )

**Comment by gerbrent** [comment]
never a bad thing to have several pairs of eyes ; )

**Comment by StefanS-O** [comment]
@kbondarev looks good to me!
