### ISSUE TITLE
Community menu & page - local links should not open in new tab/window

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#195]
### Current behaviour
Links in the Community menu AND [Community page](https://jupiterbroadcasting.net/community/) that are to local pages i.e. `jb.net/community/matrix` when followed open in a new tab/window.

### Desired behaviour
local links should be followed in the current tab/window

Todo:
* [ ] change menu link behaviour
* [ ] change [Community page](https://jupiterbroadcasting.net/community/) behaviour

**Comment by elreydetoda** [comment]
Dang, sorry @gerbrent  I though I'd done that 😅 if someone doesn't pick that up by tomorrow I can do it if you want.

Or we could leave it to someone else since you put a "good first issue" label?

**Comment by gerbrent** [comment]
@elreydetoda - it's all yours.

I typically put that label on relatively trivial changes to encourage/facilitate newcomers to contribute, but that's no reason to hold up progress!

Feel free to take this one.

**Comment by elreydetoda** [comment]
Awesome, I'll try and get to that tonight since it's just a small logic change.

**Comment by gerbrent** [comment]
note: added the [Community page](https://jupiterbroadcasting.net/community/) to this ticket aswell - same issue is present for the cards there.

**Comment by gerbrent** [comment]
> change [Community page](https://jupiterbroadcasting.net/community/) behaviour

done! nicely accomplished..

> change menu link behaviour

also done! I had some strange behaviours on this one w caching..... just a note for future testers.
