### ISSUE TITLE
No favicon on jupiterbroadcasting.com

### ISSUE THREAD

**Issue by reclaimingmytime** [JupiterBroadcasting/jupiterbroadcasting.com#198]
Currently, jupiterbroadcasting.net does not have a favicon, which means the browser displays the default icon in the browser tab:
![image](https://user-images.githubusercontent.com/35609464/181819379-d08fcca7-7336-465d-8e46-bdbf517402f0.png)

For comparison, this is what jupiterbroadcasting.com currently looks like:
![image](https://user-images.githubusercontent.com/35609464/181819517-73b4f322-c5ab-4259-ba48-64a0e0dde8f8.png)

**Comment by gerbrent** [comment]
great!

Note: the new favicon should be the JB Rocket

**Comment by gerbrent** [comment]
I'm not seeing this applied to either Firefox or Brave - any thoughts on why?

**Comment by reclaimingmytime** [comment]
Yes, there seems to be an issue with embedding the favicons. It seems like the favicons were uploaded to the server, but they have not been embedded properly.

The browser console shows the following:
```Failed to load resource: the server responded with a status of 404 (Not Found)
/favicons/favicon-32.png:1          Failed to load resource: the server responded with a status of 404 (Not Found)
/favicons/favicon-192.png:1          Failed to load resource: the server responded with a status of 404 (Not Found)
```

I have updated the links in pull request #207.

**Comment by gerbrent** [comment]
I should have spoken up sooner - sorry about that @reclaimingmytime :

The Rocket logo shouldn't be smooshed - it should *always* keep it's proportions, no exceptions. The answer here, then, is to simply place the JB Rocket within a square frame. If you need a vector file for the Rocket, I can likely provide one. Just DM me on Matrix please..

![image](https://user-images.githubusercontent.com/7018928/182744780-6b9d7492-5349-4525-a41d-51c213bdb909.png)

**Comment by gerbrent** [comment]
from our branding guidelines (can send you a copy if you ask me for it directly)

![image](https://user-images.githubusercontent.com/7018928/182882981-682aa91b-8f13-4e43-9ec3-c82f9e90c983.png)


dark mode version:

![image](https://user-images.githubusercontent.com/7018928/182883028-7d50119f-45c9-458f-b3db-6a18125f133e.png)

**Comment by reclaimingmytime** [comment]
@gerbrent Sure, I agree the correct aspect is preferable. I will message you on Matrix regarding the SVG of the rocket.

**Comment by reclaimingmytime** [comment]
@gerbrent 
> I was picturing this would be the favicon, but w the above cropping (ignoring the protected space)

Just to make sure: The favicon should also include the text "Jupiter Broadcasting"? I was going to crop the text "Jupiter Broadcasting" from the logo and just keep the rocket, because that's easily recognisable, even at 16x16px.

**Comment by gerbrent** [comment]
Chris says: Just the Rocket!

**Comment by reesericci** [comment]
It's working for me!

**Comment by ironicbadger** [comment]
<img width="137" alt="image" src="https://user-images.githubusercontent.com/2773080/184895106-238e0b2d-cc9e-4689-9b57-e4bf43ac79ef.png">

favicon appears to be blank. Is this because we moved the site to `new.jb.com`?

**Comment by ironicbadger** [comment]
Ok so the favicon works but when the tab is focused it is invisible. Here is an unfocused tab.

So perhaps the ask here is to put the icon in a square of colour so that its visible at all times?

![image](https://user-images.githubusercontent.com/2773080/184902719-0e7a149c-3e70-4014-b333-d53f166a8e7e.png)

**Comment by reesericci** [comment]
You could also change the favicon depending on if its dark or light mode
in the browser

—reese

**Comment by reesericci** [comment]
This is exactly what I was about to comment lol

—reese

**Comment by ironicbadger** [comment]
Ok dynamic favicon switching gets a +1 from me!

**Comment by gerbrent** [comment]
![image](https://user-images.githubusercontent.com/7018928/194986112-3d6e0044-681f-4407-b60f-9c022390a9a1.png)

Confirming this still needs attention!
Anyone want to work on the dynamic favicon switching™ ??

**Comment by genebean** [comment]
Y'all might find this helpful both for checking and for building all the right files via a link on their front page (I use this for my sites) https://realfavicongenerator.net/favicon_checker?protocol=https&site=www.jupiterbroadcasting.com%2F

**Comment by TheHesster** [comment]
I'm available to tackle this @gerbrent 
I'm not signed up on matrix but I can get signed up to get the svg from you.
Was planning to just use the white rocket with a background of #2a2a2a instead of dynamically switching it to dark rocket based on browser theme.

**Comment by TheHesster** [comment]
I could also look into the dynamic switching of the favicon based on browser theme.

**Comment by TheHesster** [comment]
I'm done all my work on this issue with a random svg I made with inkscape. Please ignore my incredible inkscape skills!

![JupiterLightOnDark](https://user-images.githubusercontent.com/85858098/216429448-11822c37-0fc0-4522-b60d-28d32ed89cea.png)
![JupiterDarkOnLight](https://user-images.githubusercontent.com/85858098/216429463-61170cb9-ea1a-48d1-8d34-0967f1a99941.png)

I've also done a bunch of the work to fix issues included at https://realfavicongenerator.net/favicon_checker?protocol=https&site=www.jupiterbroadcasting.com%2F as @genebean indicated.

I just need the original JB files from @gerbrent when you have a chance.

**Comment by TheHesster** [comment]
Just double checking here that I should move ahead with the white version as #ffffff?
I think that makes the most sense.
