### ISSUE TITLE
JB menu item - should be the JB logo image

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#205]
> I think that the JB menu item should be a logo image imo.

_Originally posted by @reesericci in https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/194#issuecomment-1200315126_

**Comment by gerbrent** [comment]
@reesericci - interested in this one then??

**Comment by reesericci** [comment]
Sure!

**Comment by gerbrent** [comment]
If you need a vector of the Rocket or the logo let me know (via DM on Matrix)

**Comment by reesericci** [comment]
PR submitted! #220

**Comment by gerbrent** [comment]
nice!
