### ISSUE TITLE
Verify HLS Stream URL

### ISSUE THREAD

**Issue by reclaimingmytime** [JupiterBroadcasting/jupiterbroadcasting.com#208]
The [live page](https://www.jupiterbroadcasting.com/1030/jblive/) currently links to an HLS Stream:
http://jupiter-hls.secdn.net/jupiter-channel/play/jupiter.smil/playlist.m3u8

VLC shows the running time as "00:00" and doesn't start the stream, even as a live stream is going right now (Office Hours).

I've never used an HLS stream before, so it could just be me. So, it would be great if someone with the experience can verify if the HLS stream URL is working.

**Comment by gerbrent** [comment]
added to #233

**Comment by gerbrent** [comment]
@noblepayne did you ever get the chance to check this last LUPday?

**Comment by elreydetoda** [comment]
I think this can be closed because of this: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/254

Right?

**Comment by reclaimingmytime** [comment]
I heard Wes verify that the HLS stream works on the latest LUP stream, and it works for me as well using an online HLS player.

![Screenshot 2022-08-22 at 19 18 43](https://user-images.githubusercontent.com/35609464/185981065-bce668dc-f50f-495a-9475-be56b5ef6882.png)
