### ISSUE TITLE
Community Page - platform titles misaligned

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#211]
The titles of each platform on the [Community](https://jupiterbroadcasting.net/community/) page sit at inconsistent height within the respective cards. I.e. the `Peertube` title is higher in it's card then the `Meetup` title in it's card.

This appears to be dictated by description length, pushed to the bottom of the card as a priority.

### Expected Behaviour
I would expect the titles to all hold the same horizontal position in the cards, presumably just under the fixed-size logos, and let the longest description dictate the total card length. Thus the short-description cards would have the negative space within the card be bottom-justified.

There may be two relationships here:
* [ ] all icons should be bound to the same dimensions
* [ ] all titles should site just below that bound space, all at the same relative heigh in the card
* [ ] the negative space needed to make all cards the same dimension should sit below the description on cards with shorter descriptions.

![image](https://user-images.githubusercontent.com/7018928/182742020-6a45f168-c184-44fc-a42c-497383ec68a8.png)

**Comment by Lord0fBytes** [comment]
I can work this one @gerbrent if you want to assign it.

**Comment by elreydetoda** [comment]
Thanks @Lord0fBytes ! I know that I didn't do the best for the layout on these but they're at least there :upside_down_face: (I'm normally not the best designer but a pretty good implementer :grinning: )
