### ISSUE TITLE
docs - docker dev environment setup - needs updating

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#216]
currently our README states:

> #### Using Docker
>
> To build and run the docker image:
> `make run`

Likely due to changes from #170 , our basic introductory documentation on how to use Docker is quite problematic....

``` 
> make run
make: *** No rule to make target 'run'.  Stop.
```

Would be lovely to update the documentation/README to help make the process seamless.

**Comment by elreydetoda** [comment]
Oh, sorry I either thought I'd updated that or thought it said `make dev` :sweat_smile: 

This could probably be done by someone as a good first issue, because all they have to do is change the MD from `make run` to `make dev` and then everything should work :slightly_smiling_face:

**Comment by gerbrent** [comment]
Done.

Can someone confirm that is the only required change to our dev setup documentation please?

**Comment by gerbrent** [comment]
solved by [d4f81392e426650ebbcd9b7187e0fdac63e324ae](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/249/commits/d4f81392e426650ebbcd9b7187e0fdac63e324ae)
