### ISSUE TITLE
Minify CSS

### ISSUE THREAD

**Issue by reclaimingmytime** [JupiterBroadcasting/jupiterbroadcasting.com#231]
The CSS file is currently not minified.

We might consider using the Hugo [asset minification](https://gohugo.io/hugo-pipes/minification/) feature for the CSS file as well.

Edit: It looks like the CSS is already being minified once Hugo is "in production" (maybe a config variable is changed, but I couldn't reproduce that).
https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/themes/jb/layouts/partials/head.html#L13

**Comment by reesericci** [comment]
Can I close the issue since it's being minified in prod?

**Comment by elreydetoda** [comment]
Ya @reclaimingmytime, I implemented that so it's easier to debug styling and such locally, and it is controlled by a variable during the deployment.

Here is the line in the code where the minification happens: 

https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/themes/jb/layouts/partials/head.html#L7-L20

And in the GH action I modified it to be in "production" mode i.e. here https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/.github/workflows/main.yml#L22

**Comment by elreydetoda** [comment]
If you want to use it locally just do the ` --environment prod` it locally when you do your hugo serve

**Comment by elreydetoda** [comment]
Feel free to re-open if you think you need to @reclaimingmytime , but I'm going to close this.

**Comment by reclaimingmytime** [comment]
@elreydetoda I believe there's a typo in the [GitHub Actions config file](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/.github/workflows/main.yml#L22) you linked. The correct parameter seems to be `--environment production`, not `--environment prod`.

Currently, the stylesheet on jupiterbroadcasting.net is not minified:
```html
<link rel="stylesheet" href="/css/main.css">
```
It's also not modified on my local system when I use `--environment prod`.

However, when I use the following command, I get a minified CSS file.
`hugo --config=config.toml --environment production server -D`
```html
<link rel="stylesheet" href="/css/main.min.08681d8fc594156111e1f0728a5d1816c75850d1845714b3b5c4a666251830ba.css">
```

Can you verify this?

**Comment by elreydetoda** [comment]
Huh...I guess they changed something in hugo then...that's worked for me with previous projects...looks like you're right though it's production.

I actually looked at the hugo source code and actually we don't need to specify an environment for when it goes to deploy. If we exclude the environment flag it'll default to production, when the `serve` sub-command isn't used.

You can test this with something like: `hugo --gc -d tmp/ --cleanDestinationDir`

Submitting a PR now to fix this, thanks for catching this @reclaimingmytime :slightly_smiling_face:
