### ISSUE TITLE
Live page - why a separate config/site?

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#233]
The menu, footer at https://jb-live.jupiterbroadcasting.net/ differ from the main Hugo site.

This leads me to question:
* Why is the Live page necessarily a separate hugo site?
   * seems this would only add to inconsistencies..

i.e. we have a dedicated [config.jb-live.toml](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/config.jblive.toml) - is that really necessary?

#### Expected
The Live page should feel cohesive w the rest of the site, asthough it's just another page on the JB main site..

**Comment by gerbrent** [comment]
added to #233

**Comment by reclaimingmytime** [comment]
I agree, I would also prefer the live page to be part of the main page.

When switching between both sites, the change of the menu items in the navigation becomes confusing and you need to find your orientation again on the new page.

**Comment by elreydetoda** [comment]
Don't have time to work on this yet, but this'll probably help with the consistency: https://gohugo.io/hugo-modules/configuration/#module-config-mounts

In hugo you can "mount" different types of pages to other locations (think of it like a symlink), so you should be able to do that for different files/folders.

**Comment by gerbrent** [comment]
oh sorry, my description wasn't clear enough. Adding to the initial comment to clarify.

**Comment by gerbrent** [comment]
> i.e. we have a dedicated [config.jb-live.toml](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/config.jblive.toml) - is that really necessary?

^ added this

**Comment by gerbrent** [comment]
> @gerbrent, so are you saying (with this issue) that you'd like the url to be something like: new.jb.com/live ?

this url would be completely acceptable, but is not the main intention of this ticket.
The main intention is to address the many little inconsistencies and errors we are getting from having `jb-live` have it's own `config.toml`
