### ISSUE TITLE
footer JB logo - blurry, replace with SVG

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#239]
The current logo in the footer is rather low quality. It would be lovely to replace it with an SVG, similar to what has been done in the menu via #220.

I attempted the simply duplicate the svg viewbox from `config.toml` however... it got me thinking about Hugo philosophy of "everything only exists once."

So: is there a better way to implement this such that both JB logos/svg are, in fact, only defined once and then referenced?

**Comment by gerbrent** [comment]
@reesericci since you authored #220, would you be interested in exploring this one?

**Comment by reesericci** [comment]
yeah sure

**Comment by reesericci** [comment]
I don't currently have the time to work on issues - someone else can take this on. My bad.

**Comment by pagdot** [comment]
right now it is just inline svg. It would be possible to put it in it's own svg file as a static image asset and reference the same file in both cases. Right now it uses a different logo design though.

I would be able to take a look at it if this sound fine to you :)

**Comment by reclaimingmytime** [comment]
The header logo is an inline SVG, the footer logo is currently a PNG.

A benefit of a dedicated SVG file would be that it gets cached and loads faster on subsequent page loads.

**Comment by gerbrent** [comment]
@pagdot if you're happy to take this, please do! dedicated SVG all the way...

**Comment by pagdot** [comment]
Should be fixed now with the merge of #305

**Comment by gerbrent** [comment]
thanks @pagdot !
