### ISSUE TITLE
home page - Possibly merge shows and latest episodes.

### ISSUE THREAD

**Issue by dwarf-king-hreidmar** [JupiterBroadcasting/jupiterbroadcasting.com#246]
If there were a way to only show the latest episode of each show in the latest episode list and then provide a "more" button you could drop the extra "shows" row a the top of the page and still list each of them by way of their latest episode.

**Comment by gerbrent** [comment]
related to #236.

One challenge I see with this approach would be that currently clicking on a "Show" card takes you to that Show overview, i.e. https://jupiterbroadcasting.net/show/coder-radio/ where there is some information presented that does not exist on Episode pages, i.e. https://jupiterbroadcasting.net/show/coder-radio/477/

For a new-to-JB listener, having a list of ALL of JB's offering is helpful. This could be accomplished with the menu, however is hidden by default and thus not obvious at first glance.

hmm....

#### Question
Is the current layout really that clumsy from a UX perspective? UI?

**Comment by dwarf-king-hreidmar** [comment]
I wouldn’t call it clumsy at all. I felt that having multiple of the same show in the latest episodes section just seemed a little messy and unnecessary for a landing page and that it would be cleaner if you hid all but one of the latest ep in a more section. While I was looking I thought it might be nice to combine the elements and streamline more.

**Comment by gerbrent** [comment]
Thanks for that context and experience - totally valid too. Hmm! Feels like one of those design decisions that has value and compromise either way...
