### ISSUE TITLE
DNS in Git

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#258]
### Discussed in https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/discussions/193

<div type='discussions-op-text'>

<sup>Originally posted by **reesericci** July 28, 2022</sup>
I think it would be really cool if the jb.com DNS was managed transparently in a github repo.</div>

**Comment by ironicbadger** [comment]
See [here](https://github.com/JupiterBroadcasting/infra/blob/master/ansible/roles/dns/tasks/main.yaml) which pulls in any variable from the Ansible variables [here](https://github.com/JupiterBroadcasting/infra/blob/master/ansible/group_vars/demo.yaml#L206) which match the format `Host(`synology.selfhosted.show`)` (these are compatible with the load balancer in use, Traefik).
