### ISSUE TITLE
People page - Add pagination to People page

### ISSUE THREAD

**Issue by kbondarev** [JupiterBroadcasting/jupiterbroadcasting.com#262]
https://jupiterbroadcasting.com/people/

- paginate peoples page (tl;dr: not straightforward)
  - references:
    - [Paginating PageGroups](https://gohugo.io/templates/pagination/#list-paginator-pages)
  - When using this: `{{ range (.Paginate ((where site.RegularPages "Section" "people").GroupBy "Type").Reverse ) }}`
    - errors received where
      - no paginator
![image](https://user-images.githubusercontent.com/10230166/183832534-3c4386db-8162-46b6-ba91-ad6e2d3b897f.png)
      - our custom paginator
![image](https://user-images.githubusercontent.com/10230166/183832823-c7434671-0be4-4347-a290-f7c26ee9910f.png)
      - the hugo internal paginator
![image](https://user-images.githubusercontent.com/10230166/183832679-1a23942a-f641-40b5-a55a-73456a471cc3.png)

_Originally posted by @elreydetoda in https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/252#issuecomment-1210219425_

**Comment by kbondarev** [comment]
@gerbrent I'm not sure if it's a requirement for Milestone 1.0 or could be pushed further, what do you think?

**Comment by gerbrent** [comment]
closed by #144

**Comment by elreydetoda** [comment]
This actually is for this page: https://www.jupiterbroadcasting.com/people/

Since we're displaying hosts and guests it wasn't liking the custom pagination we had when doing 2 things to paginate.

**Comment by gerbrent** [comment]
I just caught this too, and yet as usual you're very astute @elreydetoda !
Glad you're keeping my actions in check. THANKS!!!

**Comment by ChanceM** [comment]
I am working on this issue. I can actually paginate the set w/custom pagination, but I don't think it produces the desired result. It will start with the hosts and then go down the the guests. Currently this will show all hosts and one guest. Then on the second page no hosts and continue guests.

I am still doing some testing on possible alternative scenarios. What I'm thinking is do not paginate the hosts, and paginate only the guests. Number of hosts is relatively low and probably of higher importance. The number of guests is high and thus pagination is desirable.

For the group/JB: What is the desired interaction for paging?

**Comment by ChanceM** [comment]
Okay been working on a broader clean up of the people / host pages. Bellow is the proposed implementation paging onky the guests as well as adding filtering back to the page per #223. Pages have also be adjusted to fit properly on mobile.
![localhost_1313_people_](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/assets/11327907/384e40a7-f14a-4289-885e-59b3d8176bb0)
