### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#27]
use paginator... basically on each listing page :D

**Comment by gerbrent** [comment]
NICE!!! And the pagination is SO responsive/quick, really impressive.

Stretch goal: add this to the Home page aswell, since so far only applied to Show pages.

**Comment by gerbrent** [comment]
Reopening ticket for improvement.

**Comment by StefanS-O** [comment]
Alright, i think the ticket was closed because i wrote fixes #27 in the commit message :)

**Comment by StefanS-O** [comment]
I added pagination to the homepage, arranged it a bit better
