### ISSUE TITLE
Jupiter.tube embed size - larger please!

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#281]
It would be great if the Peertube embed could have a larger size. Currently feels quite small on a desktop monitor. Something akin to the default Youtube player might be a good starting point to decide on the default desktop size..

As example, here's a size-by-size with Youtube.

![image](https://user-images.githubusercontent.com/7018928/184557527-32066d1b-ec73-474c-9580-1b4e87790139.png)

**Comment by noblepayne** [comment]
@ChrisLAS suggested 960x540.

**Comment by noblepayne** [comment]
We may want a responsive or mobile-friendly version in the future, but created #282 to get things a little bigger in the meantime.

**Comment by elreydetoda** [comment]
Related #278

Maybe that can be the responsive issue
