### ISSUE TITLE
IPv6 - add Cloudflare Proxy

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#292]
see #16

Intention is to support IPv6 via Cloudflare Proxy (alongside other Cloudflare feature, caching, etc)

JB to add Cloudflare Proxying to:

* [ ] new.jb.com
* [ ] dev.jb.com
* [ ] jb.com (at time of new website publishing?)
* [ ] ... ?

**Comment by gerbrent** [comment]
@ironicbadger added proxying this AM, so just need some testing to confirm

**Comment by ironicbadger** [comment]
We were missing a setting in the Cloudflare dashboard for SSL/TLS encryption. After setting this to `Full (strict)` things are working as expected.

A couple of notes. This *requires* a valid certificate from a trusted CA. We are using lets encrypt which qualifies but self-signed certs or certs from non trusted CAs will not work.

![telegram-cloud-photo-size-1-5177193968927091236-y](https://user-images.githubusercontent.com/2773080/184907433-a9ff1bb5-352b-44d5-b6f1-def3ad70ab68.jpg)

**Comment by ironicbadger** [comment]
With regards to IPv6 I'm reticent to even touch it for now - *especially* as part of the 1.0 milestone I would argue it's not important. Very few ISPs even support IPv6!

My vote would be to defer this beyond 1.0 milestone.

**Comment by elreydetoda** [comment]
There's no need to move it to the next milestone, it's working since you turned on the DNS proxying :grin: 

https://geekflare.com/tools/tests/vn4ympfvz

![image](https://user-images.githubusercontent.com/10230166/184940932-174ba24a-df1e-46de-a8eb-1381153bfcdf.png)

**Comment by elreydetoda** [comment]
> We were missing a setting in the Cloudflare dashboard for SSL/TLS encryption. After setting this to `Full (strict)` things are working as expected.
> 
> A couple of notes. This _requires_ a valid certificate from a trusted CA. We are using lets encrypt which qualifies but self-signed certs or certs from non trusted CAs will not work.
> 
> ![telegram-cloud-photo-size-1-5177193968927091236-y](https://user-images.githubusercontent.com/2773080/184907433-a9ff1bb5-352b-44d5-b6f1-def3ad70ab68.jpg)

So, in regards to this...shouldn't flexible also work? It'll also not require you have a cert on the jb.com server (which is still good to do, but isn't necessarily required)

**Comment by ironicbadger** [comment]
> So, in regards to this...shouldn't flexible also work? It'll also not require you have a cert on the jb.com server (which is still good to do, but isn't necessarily required)

Yes, however for prod stricter is better imho.

**Comment by elreydetoda** [comment]
Ya, but when you put it to strict mode it'll be for the whole domain not just jb.com but even the new.jb.com, dev., etc..., which isn't a bad thing IMO (I'm all for more security) but just want to make sure you/JB are aware of that :upside_down_face:
