### ISSUE TITLE
Network Membership @ jupiter.party not listed on JB.com

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#3]
Network Membership @ Jupiter.party: 
* [x] not listed on JB.com or LUP.com, or anywhere else.

**Comment by gerbrent** [comment]
Would someone be willing to do some simple content editing?
Likely a great first issue for someone looking to get involved.

* [ ] move the " Network Membership". "Show Memberships" and "Gift Memberships" sections to be ABOVE the "Special Features" list.
* [ ] remove the internal links to the shows - the blue/link colour is distracting....... or, perhaps it might look fine? Opinions?

Reasons:
If I came to the page here after hearing about the memberships in one of the shows, I might want to jump to the *Buy Now!* process. If I would like to read more about the implications, it's logical to have that follow..... Further down (the rabbit hole) = more explanation.

**Comment by reesericci** [comment]
It might make more sense to remove jupiter.party as a seperate site and instead have a page on the main JB.com site directing to memberful.

**Comment by gerbrent** [comment]
well, it *is* helpful to be able to refer to "Jupiter.Party" on air, and we've sorta branded the network memberships as such at this point. ....Join the Party!™

**Comment by gerbrent** [comment]
OOOHHHH... I see what you're saying now.

I take it back: GREAT idea. 

Jupiter.Party is hosted independently, and features a few links as redirects to Memberful.
Instead it should link directly here, to our Memberships page. Got it!

Will make a ticket for it.

I'll make a new issue out of the above comment I added aswell - this current issue is..... vague and of a simpler time ; )
