### ISSUE TITLE
Missing padding on Shows Home Page

### ISSUE THREAD

**Issue by histamineblkr** [JupiterBroadcasting/jupiterbroadcasting.com#308]
It’s probably in a class or padding config (css/sass/or?) somewhere, but left padding seems to be missing. It was present on any show I clicked on.
![DB300CCC-6A16-48D1-BE9D-5555F5ADEF19](https://user-images.githubusercontent.com/5628330/185477784-6628f04f-04e8-422d-be48-5a76369cda37.jpeg)

When I’m not working and free, I can try to chase down the config and make a PR, but figured I get this written since someone who’s already working on it will know right where it is and can fix it in minutes. 🙂

oh I should mention this was on my iPhone on Safari.

**Comment by histamineblkr** [comment]
On full screen desktop it looks fine:
![image](https://user-images.githubusercontent.com/5628330/185500365-d45674af-1d56-4438-99c6-0c4cba36f1de.png)

but when we minimze, we see the padding is nearly 0:
![image](https://user-images.githubusercontent.com/5628330/185500442-4bf9d465-d2d8-40b5-ae17-7a8122c39884.png)

**Comment by histamineblkr** [comment]
Looks to be the `container` class. Maybe specifically:
```
.container {
  flex-grow: 1;
  margin: 0 auto;
    margin-top: 0px;
    margin-right: auto;
    margin-bottom: 0px;
    margin-left: auto;
  position: relative;
  width: auto;
}
```
`margin-left: auto` perhaps?

**Comment by histamineblkr** [comment]
This is probably a very low priority since there are 84 other open issues. If I knew what to change, I would create a PR, but I am unsure. I may create a dev instance and try to figure it out since I do have docker setup with web access I could mess around with.

**Comment by CGBassPlayer** [comment]
That would be my fault. After someone introduced the icons, they were stretched across the show description and it did not look good at all. I pushed them closer together and kind of forgot about it. 

I can work on this with my plan to keep the icons close together, just center it across the description.

**Comment by histamineblkr** [comment]
@CGBassPlayer nice sounds good. When you have that specific commit do you mind posting it or tying it to this somehow so I can see what you did to fix this issue?

**Comment by CGBassPlayer** [comment]
Absolutely! I haven't been able to do it just yet (life got in the way last week), I'll make sure the PR I include it in is mentioned here.

**Comment by gerbrent** [comment]
ahhh...... so much better. Tested and approved!

![image](https://user-images.githubusercontent.com/7018928/188284615-8288a925-ddd4-4012-9ceb-d5b58283b281.png)
