### ISSUE TITLE
Kiwi IRC not working properly

### ISSUE THREAD

**Issue by elreydetoda** [JupiterBroadcasting/jupiterbroadcasting.com#316]
I'm getting ready to submit a PR for #233 and it's related issues, and I went to go test the functionality of kiwiirc.com's embed and it gave me a 502 error on the new site. So, without my PR the embed is broken (just wanted to make note of it before I submit my PR and gets merged :sweat_smile: )

![image](https://user-images.githubusercontent.com/10230166/185516985-04f688af-dc6e-4498-a0bc-7b0c131c6577.png)

![image](https://user-images.githubusercontent.com/10230166/185517194-935992d3-50da-46da-94c2-74ebfad1bc7c.png)

From the dev tools under the `Headers` & Payload sections:
```
# General
Request URL: https://do-a.clients.kiwiirc.com/client/transport/?EIO=3&transport=polling&t=1660868636079-0
Request Method: GET
Status Code: 502 
Referrer Policy: strict-origin-when-cross-origin

# Response Headers
Connection: keep-alive
Content-Length: 568
Content-Type: text/html
Date: Fri, 19 Aug 2022 00:23:56 GMT
Server: nginx

# Request Headers
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Host: do-a.clients.kiwiirc.com
Origin: https://kiwiirc.com
Referer: https://kiwiirc.com/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="104"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36

# Query String Parameters
EIO: 3
transport: polling
t: 1660868636079-0
```

**Comment by reclaimingmytime** [comment]
I mentioned this issue in https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/163#issuecomment-1207173045.

Once https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/317 is merged, I can take a look at replacing the old Kiwi IRC client with the "next client".

**Comment by reclaimingmytime** [comment]
The Kiwi next client connects fine on my local system and I don't get the "xhr poll error" anymore.

The only downside is that the color of the login form doesn't fit with the rest of the page:

![image](https://user-images.githubusercontent.com/35609464/185636342-78aee120-62da-4a9f-b1fb-cc53208bda60.png)

Is this something we can accept?

**Comment by elreydetoda** [comment]
Just tagging some relevant people.

@Lord0fBytes  & @reesericci had been doing a bunch of design stuff.

@gerbrent  had been the main JB contact.

@reclaimingmytime , if you don't mind doing a ["Draft PR"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests) against the repo that'd let people know where to pull it down and play with things locally.

**Comment by reclaimingmytime** [comment]
@elreydetoda A draft pull request is a great idea. You can find the change in #321

**Comment by gerbrent** [comment]
@reclaimingmytime - just did some local testing and it seems to work great and the colours are very acceptable. Especially since it actually is a functional client compared to the old Kiwi ; )
