### ISSUE TITLE
Guest page is larger than viewport

### ISSUE THREAD

**Issue by TeamLinux01** [JupiterBroadcasting/jupiterbroadcasting.com#324]
The page on my phone (Vivaldi on Moto G7 Plus) is slightly wider than the viewport when viewed with portrait mode.

![Screenshot_20220820-133907_Vivaldi_Browser.png](https://user-images.githubusercontent.com/43735175/185759918-f24d5e0e-9db2-4cc0-882c-14332d306c5b.png)

![Screenshot_20220820-134508_Vivaldi_Browser.png](https://user-images.githubusercontent.com/43735175/185759934-cef414ab-d515-4155-968b-a3a159b1bccf.png)

**Comment by ChanceM** [comment]
@TeamLinux01 can you check this now that #397 has been applied?

**Comment by TeamLinux01** [comment]
It seems to be fixed. Thank you all.

**Comment by ChanceM** [comment]
@gerbrent this one can be closed.
