### ISSUE TITLE
Header is too large

### ISSUE THREAD

**Issue by reesericci** [JupiterBroadcasting/jupiterbroadcasting.com#33]
The header on the top of the page is too large. I want to see the episodes right away, not a giant logo and a low-contrast subtitle.

Here's a mockup of what it would look like with a smaller header:

![image](https://user-images.githubusercontent.com/19589006/177406175-df48ee85-afcd-4531-9269-033e6b7e4aa1.png)

**Comment by StefanS-O** [comment]
Yeah true, i am currently working on the HTML / SASS files to make it look nicer. I already made the header smaller and started a new branch to make the whole template look nicer.

**Comment by reesericci** [comment]
Perfect!
