### ISSUE TITLE
Change Github Website Link?

### ISSUE THREAD

**Issue by GL513** [JupiterBroadcasting/jupiterbroadcasting.com#330]
Unless the link is there for watching traffic stats, it would be nice to not have a redirect, which is only slowing down the actual page loading.

![GL513_22-08-23_11:26:50](https://user-images.githubusercontent.com/83085846/186199053-43573582-d159-4ffa-b234-0e855586f31f.png)

**Comment by gerbrent** [comment]
good catch!

**Comment by gerbrent** [comment]
Fixed!
