### ISSUE TITLE
Niche: Margin Problem

### ISSUE THREAD

**Issue by GL513** [JupiterBroadcasting/jupiterbroadcasting.com#332]
I poked around and broke something sorta...

When setting outrageous dimensions, the margins don't want to work properly. the Dimensions are stated at the top of the screenshot, 700px wide, 4000px tall.
![GL513_22-08-23_12:08:02](https://user-images.githubusercontent.com/83085846/186208026-b7209ce9-0dfc-4193-954d-7d05c6c57429.png)

**Comment by GL513** [comment]
Don't mind the way the text being all squiggly, there's something wrong on my end that I can't seem to fix.

**Comment by CGBassPlayer** [comment]
The icons not having the padding is related to #308 and I do plan on fixing that soon. 

As far as the text not having the margins, good find in my opinion.

**Comment by CGBassPlayer** [comment]
@gerbrent I think this issue should be fixed by PR #372

**Comment by gerbrent** [comment]
good catch @CGBassPlayer !
