### ISSUE TITLE
Subscription - add button to Episode pages

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#333]
I really like this option:

![image](https://user-images.githubusercontent.com/7018928/186578543-9a383ddf-8f1a-4fa5-b694-8fbb7fab952d.png)

Anyone want to implement this?
Each Episode page from a Show should link to the appropriate subscribe page, w similar button to the "Support" button. 

_Originally posted by @gerbrent in https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/306#issuecomment-1226777039_

**Comment by DronSKM044** [comment]
Hi! I want to try to resolve this issue.

**Comment by gerbrent** [comment]
amazing @DronSKM044 - please do! Let us know if you need anything.

**Comment by DronSKM044** [comment]
Hi, guys. Three days ago I sent resolved issue. If something is wrong, please give me feedback. If everything is ok, I want to continue helping you with other issues.

**Comment by gerbrent** [comment]
I see it!
We don't always test or merge PRs right away, since it's nice to have a few people who are experts in that area have a look. Unfortunately, many of us have been pretty busy w other priorities - some w work, some w other pressing issues around the website code here, but certainly doesn't mean we don't value your contribution. 

Your addition is appreciated! 

I also commented a few in the PR..

**Comment by DronSKM044** [comment]
Ok. I understand, no problem :). I left a few comments in the PR

**Comment by gerbrent** [comment]
FYI, a natural evolution of this work, assuming @346 merges, would be https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/404

**Comment by ChanceM** [comment]
I know there is a PR in process for this but just wanted to throw this out there for thought. What about providing the links directly in the page?

![image](https://user-images.githubusercontent.com/11327907/190710572-c430550f-ad72-4164-9f1e-45371925101a.png)

**Comment by elreydetoda** [comment]
Personally @ChanceM  I appreciate the efficiency of not navigating to a new page, but I don't know about the style...it seems a bit overbearing to me but that might just be the bright blue color.

I'm also not a designer so I'll leave the design things to @reesericci and @gerbrent  😅

**Comment by ChanceM** [comment]
> I'm also not a designer so I'll leave the design things to @reesericci and @gerbrent  😅

@elreydetoda 🤷‍♂️ I'm just going with the "brand" colors established.

**Comment by reesericci** [comment]
I think having two buttons of the same weight right next to each other is kinda odd

**Comment by ChanceM** [comment]
> I think having two buttons of the same weight right next to each other is kinda odd

That's how it is currently I was just proposing a dropdown with the links to save having to load a new page.
