### ISSUE TITLE
Subscribe - links should open in new window/tab

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#337]
Currently links to other podcast directories - i.e. Apple Podcasts, Castbox, etc -  in ./SHOW/subscribe open in the current window/tab. These should not take the listener away from the JB website, and thus should instead open a new window/tab.

https://new.jupiterbroadcasting.com/show/linux-unplugged/subscribe/

depends on #336 
tracked in #66

**Comment by hack13** [comment]
Since this was an easy change related to the work I just did with #336 I have added this change to that same PR
