### ISSUE TITLE
On-air alert mockup

### ISSUE THREAD

**Issue by reesericci** [JupiterBroadcasting/jupiterbroadcasting.com#34]
I made a mockup for what a large item at the top of the page would look like to advertise a currently-live show:

![image](https://user-images.githubusercontent.com/19589006/177410609-17f12d03-673e-4048-bb1e-82cc715c36f5.png)

--reese

**Comment by reesericci** [comment]
This could tie into Jbot to update the site whenever !start_show is called

**Comment by gerbrent** [comment]
great all around!

Maybe then JBot would need some attention...................

**Comment by reesericci** [comment]
There's still some work to be done on it, but it's a good start

**Comment by reesericci** [comment]
Blocked by #41

**Comment by reclaimingmytime** [comment]
@reesericci From https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/122#issuecomment-1221154780:
> Could this work for putting an alert on the page

Yes, we could to use that JSON API: https://jupiter.tube/api/v1/video-channels/live/videos?isLive=true&skipCount=false&count=1&sort=-createdAt.

The main downside is that the PeerTube API does not know the show name.

However, _PreviewPath_ in the API can be used for the preview image, e.g. https://jupiter.tube/lazy-static/previews/35d4c946-0816-4a3b-b806-3c56ea3d40a0.jpg

<details><summary>An example of the JSON output of when Coder Radio was live</summary>

```json
{
  "total": 1,
  "data": [
    {
      "id": 54,
      "uuid": "9f77b37d-ae21-45ba-bd82-cdb2846aa1a9",
      "shortUUID": "kG81bksrxHN2gx3LKeAmnp",
      "url": "https://jupiter.tube/videos/watch/9f77b37d-ae21-45ba-bd82-cdb2846aa1a9",
      "name": "Coder 480 - It's Microsoft's Move Now",
      "category": {
        "id": 15,
        "label": "Science & Technology"
      },
      "licence": {
        "id": 5,
        "label": "Attribution - Non Commercial - Share Alike"
      },
      "language": {
        "id": "en",
        "label": "English"
      },
      "privacy": {
        "id": 1,
        "label": "Public"
      },
      "nsfw": false,
      "description": "Why it's time to get real about it .Net 7, and why it's Microsoft's moment to make their next move. ",
      "isLocal": true,
      "duration": 0,
      "views": 24,
      "viewers": 14,
      "likes": 0,
      "dislikes": 0,
      "thumbnailPath": "/static/thumbnails/4583aec3-0e15-40ee-958f-4a36b53f2276.jpg",
      "previewPath": "/lazy-static/previews/35d4c946-0816-4a3b-b806-3c56ea3d40a0.jpg",
      "embedPath": "/videos/embed/9f77b37d-ae21-45ba-bd82-cdb2846aa1a9",
      "createdAt": "2022-08-22T15:09:07.309Z",
      "updatedAt": "2022-08-22T16:43:09.287Z",
      "publishedAt": "2022-08-22T15:46:48.577Z",
      "originallyPublishedAt": null,
      "isLive": true,
      "account": {
        "id": 3,
        "displayName": "JBLive Stream",
        "name": "jblive",
        "url": "https://jupiter.tube/accounts/jblive",
        "host": "jupiter.tube",
        "avatars": [
          {
            "width": 48,
            "path": "/lazy-static/avatars/e4d17e7f-a144-4a4a-b5d8-b297b06b727f.png",
            "createdAt": "2022-06-07T23:43:56.565Z",
            "updatedAt": "2022-06-07T23:43:56.565Z"
          },
          {
            "width": 120,
            "path": "/lazy-static/avatars/1340f3e9-d0a7-4bc4-bcbd-a8c865eaf1b8.png",
            "createdAt": "2022-05-30T20:36:19.005Z",
            "updatedAt": "2022-05-30T20:36:19.005Z"
          }
        ],
        "avatar": {
          "width": 48,
          "path": "/lazy-static/avatars/e4d17e7f-a144-4a4a-b5d8-b297b06b727f.png",
          "createdAt": "2022-06-07T23:43:56.565Z",
          "updatedAt": "2022-06-07T23:43:56.565Z"
        }
      },
      "channel": {
        "id": 2,
        "name": "live",
        "displayName": "live",
        "url": "https://jupiter.tube/video-channels/live",
        "host": "jupiter.tube",
        "avatars": [
          {
            "width": 48,
            "path": "/lazy-static/avatars/8acfd2a2-ab4e-48aa-990c-3156a2765d2e.png",
            "createdAt": "2022-06-07T23:43:56.607Z",
            "updatedAt": "2022-06-07T23:43:56.607Z"
          },
          {
            "width": 120,
            "path": "/lazy-static/avatars/e9bcfdb7-90a2-479c-b1da-1ab0e5fc9442.png",
            "createdAt": "2022-05-30T20:38:33.632Z",
            "updatedAt": "2022-05-30T20:38:33.632Z"
          }
        ],
        "avatar": {
          "width": 48,
          "path": "/lazy-static/avatars/8acfd2a2-ab4e-48aa-990c-3156a2765d2e.png",
          "createdAt": "2022-06-07T23:43:56.607Z",
          "updatedAt": "2022-06-07T23:43:56.607Z"
        }
      }
    }
  ]
}
```
</details>

**Comment by reesericci** [comment]
In the JSON you sent me, data.name exists

—reese

On August 22, 2022, Bananaman ***@***.***> wrote:
> @reesericci <https://github.com/reesericci> From #122 (comment)
> <https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/122#issuecomment-
> 1221154780>:
>
> > Could this work for putting an alert on the page
> >
>
> Yes, we could to use that JSON API:
> <https://jupiter.tube/api/v1/video-
> channels/live/videos?isLive=true&skipCount=false&count=1&sort=-
> createdAt>.
>
> The main downside is that the PeerTube API does not know the show
> name.
>
> However, PreviewPath in the API can be used for the preview image,
> e.g. <https://jupiter.tube/lazy-static/previews/35d4c946-0816-4a3b-
> b806-3c56ea3d40a0.jpg>
>
> An example of the JSON output of when Coder Radio was live
> { "total": 1, "data": [ { "id": 54, "uuid": "9f77b37d-ae21-45ba-bd82-
> cdb2846aa1a9", "shortUUID": "kG81bksrxHN2gx3LKeAmnp", "url":
> "https://jupiter.tube/videos/watch/9f77b37d-ae21-45ba-bd82-
> cdb2846aa1a9", "name": "Coder 480 - It's Microsoft's Move Now",
> "category": { "id": 15, "label": "Science & Technology" }, "licence":
> { "id": 5, "label": "Attribution - Non Commercial - Share Alike" },
> "language": { "id": "en", "label": "English" }, "privacy": { "id": 1,
> "label": "Public" }, "nsfw": false, "description": "Why it's time to
> get real about it .Net 7, and why it's Microsoft's moment to make
> their next move. ", "isLocal": true, "duration": 0, "views": 24,
> "viewers": 14, "likes": 0, "dislikes": 0, "thumbnailPath":
> "/static/thumbnails/4583aec3-0e15-40ee-958f-4a36b53f2276.jpg",
> "previewPath": "/lazy-static/previews/35d4c946-0816-4a3b-b806-
> 3c56ea3d40a0.jpg", "embedPath": "/videos/embed/9f77b37d-ae21-45ba-
> bd82-cdb2846aa1a9", "createdAt": "2022-08-22T15:09:07.309Z",
> "updatedAt": "2022-08-22T16:43:09.287Z", "publishedAt": "2022-08-
> 22T15:46:48.577Z", "originallyPublishedAt": null, "isLive": true,
> "account": { "id": 3, "displayName": "JBLive Stream", "name":
> "jblive", "url": "https://jupiter.tube/accounts/jblive", "host":
> "jupiter.tube", "avatars": [ { "width": 48, "path": "/lazy-
> static/avatars/e4d17e7f-a144-4a4a-b5d8-b297b06b727f.png", "createdAt":
> "2022-06-07T23:43:56.565Z", "updatedAt": "2022-06-07T23:43:56.565Z" },
> { "width": 120, "path": "/lazy-static/avatars/1340f3e9-d0a7-4bc4-bcbd-
> a8c865eaf1b8.png", "createdAt": "2022-05-30T20:36:19.005Z",
> "updatedAt": "2022-05-30T20:36:19.005Z" } ], "avatar": { "width": 48,
> "path": "/lazy-static/avatars/e4d17e7f-a144-4a4a-b5d8-
> b297b06b727f.png", "createdAt": "2022-06-07T23:43:56.565Z",
> "updatedAt": "2022-06-07T23:43:56.565Z" } }, "channel": { "id": 2,
> "name": "live", "displayName": "live", "url":
> "https://jupiter.tube/video-channels/live", "host": "jupiter.tube",
> "avatars": [ { "width": 48, "path": "/lazy-static/avatars/8acfd2a2-
> ab4e-48aa-990c-3156a2765d2e.png", "createdAt": "2022-06-
> 07T23:43:56.607Z", "updatedAt": "2022-06-07T23:43:56.607Z" }, {
> "width": 120, "path": "/lazy-static/avatars/e9bcfdb7-90a2-479c-b1da-
> 1ab0e5fc9442.png", "createdAt": "2022-05-30T20:38:33.632Z",
> "updatedAt": "2022-05-30T20:38:33.632Z" } ], "avatar": { "width": 48,
> "path": "/lazy-static/avatars/8acfd2a2-ab4e-48aa-990c-
> 3156a2765d2e.png", "createdAt": "2022-06-07T23:43:56.607Z",
> "updatedAt": "2022-06-07T23:43:56.607Z" } } } ] }

—
Reply to this email directly, view it on GitHub
<https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/34#issuecomment-
1222718584>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AEVOPDQFH327GAWVDAH2GF3V2O42XANCNFSM52XMBSWQ>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by reclaimingmytime** [comment]
@reesericci 
> In the JSON you sent me, data.name exists

True. I guess instead of the show name, we can have the banner mention the entire stream name, e.g. "'Coder 480 - It's Microsoft's Move Now' is currently on the air".

**Comment by reesericci** [comment]
perfect! Does this make #41 obsolete then?

**Comment by reesericci** [comment]
@gerbrent

**Comment by gerbrent** [comment]
You tell me! Sounds like a good way to go, but you likely have a better judgement of the best approach.

Simplistic, and straightforward via the Peertube API sounds useful and a reasonable way to solve this.

Thoughts?

**Comment by reesericci** [comment]
I personally like the PeerTube system - but the JBot idea has some benefits. It really depends on how committed JB is to using PeerTube for its live streams vs gammabot/jbot. The JBot would be able to alert the site immediately - so we could set up push notifs, and it's not dependent on peertube.

If anything, the PeerTube system is faster to implement and we can revisit this later. I'm saying go with PeerTube and just get some alert system off the ground.

**Comment by gerbrent** [comment]
I agree - Peertube is working great so far for our purposes so I think it's here to stay.

JBot is outdated (thus far, as you know) and being potentially replaced by Gammabot.
Gammabot is relatively new, and works fairly well so far but still needs more testing and features (potentially).

Lets do the Peertube option.
If anyone is willing to tackle that, say yay!

**Comment by reclaimingmytime** [comment]
@reesericci Do you have the HTML code of the mockup you made from the screenshot in the first post? That might be so someone working on this feature doesn't have to re-create that alert.

**Comment by reesericci** [comment]
Unfortunately I don't have it anymore. It was just some inspect code.

**Comment by gerbrent** [comment]
feature completed by #378
