### ISSUE TITLE
Office Hours - Show page contact button leads to 404

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#341]
"contact" link for [Office Hours Show page](https://new.jupiterbroadcasting.com/show/office-hours/) currently links to https://www.officehours.hair/contact  which doesn't exist, see #184 

We should instead have it link to ./contact

We can decide later to move it to  https://www.officehours.hair/contact as is customary for the other Show pages.. based on decisions in #184

**Comment by reclaimingmytime** [comment]
I'm going to link this just to _/contact_ for now.

We might change it to auto-select the correct dropdown in the contact form when we implement https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/206.

**Comment by reclaimingmytime** [comment]
I made the change locally, but I'm going to wait until https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/348 is merged so we don't run into any merge requests with the file `office-hours/index.md`.

**Comment by gerbrent** [comment]
merged, so go ahead @reclaimingmytime  - in the future, you can make a draft PR so at least we can review it, and improve the PR approval workflow. But, this works.

**Comment by reclaimingmytime** [comment]
> in the future, you can make a draft PR so at least we can review it, and improve the PR approval workflow.
Right, I keep forgetting that's an option. 😅 

I guess I could have committed the changes to a new branch in my fork and create a pull request from that branch, then merged the master branch into the feature branch to avoid conflicts. I wouldn't need a draft pull request then.

**Comment by gerbrent** [comment]
right! that's even better..
🎉
