### ISSUE TITLE
menu - when condensed into hamburger, RSS Feeds submenu not functional

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#343]
![menu - rss feeds](https://user-images.githubusercontent.com/7018928/186778088-34fc0e5b-b38a-47b4-99c6-715312a2f87f.gif)

**Comment by reclaimingmytime** [comment]
Possibly a duplicate of https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/315

**Comment by gerbrent** [comment]
nice catch, and embarrassing considering I suggested it's creation ; )

closing this issue.
