### ISSUE TITLE
Footer has a placeholder in the center

### ISSUE THREAD

**Issue by genebean** [JupiterBroadcasting/jupiterbroadcasting.com#357]
I can’t imagine this is intentional 

![F3C797DD-C0CB-4F24-A36A-BF0029A940D7](https://user-images.githubusercontent.com/966789/187552351-47ac26a0-980b-45ca-b69f-5261845e276c.jpeg)

**Comment by suorcd** [comment]
It is also on the desktop website.
![Screenshot from 2022-08-30 21-03-58](https://user-images.githubusercontent.com/60907848/187590337-5fb6ff45-8bde-4e5e-8051-a9a5ab81ddcf.png)

**Comment by dcowan-london** [comment]
https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/6698928166a7b027e2e84ee1aa5db7f7b53cdafa/config.toml#L202

**Comment by gerbrent** [comment]
great!

So..... what should we put there? ; )

**Comment by tjkrz** [comment]
I think I'd remove it, if there's nothing obvious to include.

**Comment by gerbrent** [comment]
#395 temporarily hides the above placeholders, but more attention should be given on the overall footer design - since now there's a rather large gap in the centre ; )
