### ISSUE TITLE
Front page rendering errors on mobile chrome

### ISSUE THREAD

**Issue by BeardedTek** [JupiterBroadcasting/jupiterbroadcasting.com#360]
Not sure exactly what's going on, but if a picture is worth 1000 words, then a couple video clip have to be worth a novel.

Mobile Chrome 104
Android 12
Samsung Galaxy S20+

I have cleared storage and cache, force stopped chrome and tried to reload the page but it still happens

https://user-images.githubusercontent.com/93575915/187566469-d7e18c73-98d5-4fff-aaa1-2f21c06624ee.mp4

If I navigate to the 2nd page it seems to work fine

https://user-images.githubusercontent.com/93575915/187567309-7d1c0e63-9de1-46e0-8cff-082c875f19d6.mp4

Let me know if there's anything I can do to help!

**Comment by elreydetoda** [comment]
wow...I hate browsers.... 🤦

Have you tried in an incognito tab? ( only other thing I could think of, even though clearing the cache should have fixed it...)

**Comment by BeardedTek** [comment]
Well, now this morning it is only accessible from www.jupiterbroadcasting.com and it works.

**Comment by elreydetoda** [comment]
> Well, now this morning it is only accessible from [www.jupiterbroadcasting.com](http://www.jupiterbroadcasting.com) and it works.

Yep, that's currently expected (related: #361)

Do you mind closing this issue @BeardedTek, since it sounds like this issue is resolved? If it's not please let us know what else is going on related to this issue :slightly_smiling_face:

**Comment by BeardedTek** [comment]
I know especially mobile chrome does some weird stuff with caching.  When developing my site I swear there's a secret cache you can't clear.
