### ISSUE TITLE
Scrape not triggering deployment

### ISSUE THREAD

**Issue by elreydetoda** [JupiterBroadcasting/jupiterbroadcasting.com#365]
I noticed (since I was looking for breakages) that when the [last scrape action happened](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/commit/e708639b2fac63754911954f556a59503c2e9fad), that it didn't trigger a "Deploy to Production" action... :thinking: 

You can see there is no :heavy_check_mark: or :x: next to the deployment:

![image](https://user-images.githubusercontent.com/10230166/187660105-b1dc23dd-fd47-403a-a400-746ae35fb86f.png)

At the time of writing this issue I also validated it didn't deploy by checking the direct downloads links for the coder radio show's last episode: https://www.jupiterbroadcasting.com/show/coder-radio/480/

Which still currently has the downloads
![image](https://user-images.githubusercontent.com/10230166/187660913-7bb71133-4933-46d1-b353-9e349fdfaa76.png)

But according to the scraper commit shouldn't:

https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/commit/e708639b2fac63754911954f556a59503c2e9fad#diff-95a9098aad54fe8528f8bd55298e85bd09ad14e78b5dc2de01e3f515bd60e17dL53-R57

**Comment by gerbrent** [comment]
possible duplicate: #371
