### ISSUE TITLE
Redirect jblive.tv

### ISSUE THREAD

**Issue by reclaimingmytime** [JupiterBroadcasting/jupiterbroadcasting.com#368]
http://jblive.tv redirects to the old WordPress URL: https://www.jupiterbroadcasting.com/1030/jblive/

This should redirect to https://www.jupiterbroadcasting.com/live/

**Comment by ChrisLAS** [comment]
DNS has been updated, and it looks like it's already working on my end. 

Nice catch :heavy_check_mark:
