### ISSUE TITLE
🚨 ⚠️  Matrix Federation Broken due to missing .well-known dirctory and contents. JB chat down 🚨 ⚠️ 

### ISSUE THREAD

**Issue by ChrisLAS** [JupiterBroadcasting/jupiterbroadcasting.com#381]
Seems we broke Matrix federation when we switched over to the new site. Lurking in the file depths of our old site was a file and folder structure that verified our server to the Matrix federation. 

Some more info here: https://matrix.org/docs/spec/server_server/r0.1.0.html#resolving-server-names

I've grabbed our old .well-known folder with its files. But I have NO idea how something like that gets deployed in this setup. In our previous setup, that lived in the root web directory.

But we need this done ASAP, since it's been since Tuesday evening our Matrix service has been down for the community and is impacting show production directly. 🚨 

My snag of the old files: https://files.horse/s/YPKJfJQ6XiKQMLk

**Comment by noblepayne** [comment]
Attempted to add our previous well-known delegation setup as a static asset.

**Comment by ChrisLAS** [comment]
Quick fix with static assets did NOT work, re-opening this issue.

**Comment by noblepayne** [comment]
Looks like it WAS working for the `www`  domain, but not the root. I've updated the cloudflare page rule that is responsible for that forwarding to pass through `/*`, and at least according the [federation tester](https://federationtester.matrix.org/#jupiterbroadcasting.com) looks like we are back in business.

**Comment by elreydetoda** [comment]
@noblepayne , did you update it with `$1` like how I'd screenshot'ed in [this comment](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/358#issuecomment-1233341553)?

Just want to know so we can update this PR: https://github.com/JupiterBroadcasting/infra/pull/9

It'll make sure terraform doesn't wipe out the manual change in future runs :sweat_smile: 

Also, we should integrate an E2E test (and maybe uptime kuma (but that might be overkill)) to make sure that all future deployments have this file in it with the expected response (the json blob from #382). We **definitely** don't want to break the matrix configuration again... :sweat_smile:

**Comment by noblepayne** [comment]
@elreydetoda 
> Also, we should integrate an E2E test

Saw your work on this, thank you!

> Also might want to consider doing some type of periodic check on the federation tester 

Was thinking the same! :brain: 

> did you update it with $1 like how I'd screenshot'ed

Yup!

> Just want to know so we can update this PR

Updated :+1:
