### ISSUE TITLE
Create a 404 page

### ISSUE THREAD

**Issue by CGBassPlayer** [JupiterBroadcasting/jupiterbroadcasting.com#388]
Currently there is no 404 page defined in the `404.html` and when a user hits a 404 they get an empty page with `404 page not found` text.

![Current 404 page](https://user-images.githubusercontent.com/34293941/188311898-ba36486c-26d1-4d13-a761-1cf2f4eb2e39.png)

Anyone have ideas for what the 404 page should look like?

**Comment by elreydetoda** [comment]
I think we should bring back the 404 from the old website! 

![image_20220904094906.png](https://user-images.githubusercontent.com/10230166/188316940-0d856b78-6852-4dd2-81a3-0f52764e8b30.png)

[source](https://matrix.to/#/!rDlEtonuSythLzmxQL:jupiterbroadcasting.com/$_vXpm7imvRu30MveOKaDNZYj9g921bf2AvimogjVBb0?via=matrix.org&via=jupiterbroadcasting.com&via=0x6b.dev)

**Comment by gerbrent** [comment]
YYYYEEEEEESSSSSS!

I *may* have downloaded the Unicorn before we switched everything over to Hugo ; )

**Comment by CGBassPlayer** [comment]
I never used the old site so I never got to experience the unicorn and I LOVE it! I think that would make a fantastic 404 page. Almost makes you want to get a 404!

**Comment by gerbrent** [comment]
I suppose the question becomes: Who wants to implement this? Should be fairly simple, and I can provide the high-res 404-nicorn when needed...

**Comment by gerbrent** [comment]
....uploaded!

[static/images/backgrounds/404-unicorn.jpg](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/static/images/backgrounds/404-unicorn.jpg)

**Comment by CGBassPlayer** [comment]
I could take care of this. What page(s) would be a good reference point to go off of when building this one?

**Comment by gerbrent** [comment]
likely one of the simple ones, like Boost or Membership. Also, thanks!!

**Comment by elreydetoda** [comment]
Also, hugo has a special template for 404 pages: https://gohugo.io/templates/404/

**Comment by CGBassPlayer** [comment]
Just as update so far...

Here is the Desktop 404
![Desktop 404](https://user-images.githubusercontent.com/34293941/190034507-14dc988c-4823-4890-85f0-6d0089cf948f.png)

And here is the mobile
![Mobile 404](https://user-images.githubusercontent.com/34293941/190034646-dbd7074f-01f0-4872-ad3f-282252b0aace.png)

Pretty bare bones at the moment...
```html
<section class="hero is-large">
  <p class="title has-text-centered mb-3">404 Page Not Found</p>
  <img src="images/backgrounds/404-unicorn.jpg"/>
</section>
```
...but I am looking through the Bulma documentation to see how to make this a little bit better. I am trying to make it look close to the 404 on the old website, but I am not 100% sure if I can get the 404 banner across the bottom yet.

**Comment by ChanceM** [comment]
I actually think this looks a bit cleaner and is an homage to the original while being nice and clean.

But for some reason (my 2yr old) this is what I [hear](https://www.youtube.com/watch?v=17o1OlroNSE ) when I see this.

**Comment by CGBassPlayer** [comment]
If we like it, I am fine with leaving it as is. Let me know what you guys think should be changed as well. I'm very open to suggestions!

**Comment by gerbrent** [comment]
Looks good to me! Love it.
