### ISSUE TITLE
Issue and/or PR Templates

### ISSUE THREAD

**Issue by CGBassPlayer** [JupiterBroadcasting/jupiterbroadcasting.com#390]
Something I think would be useful for people users new to contributing to open source would be templates for creating issues and maybe PRs. I don't think it needs to be anything extravagant, but something to just let them know what they should put in  when submitting an issue and possibly add some auto tagging.

Initial idea I am thinking is:
* Bug Report
  * What is the bug
  * What device (Phone, tablet, desktop, etc.)
  * Steps to reproduce
  * Screenshots

* Feature Request
  * Describe the feature
  * Is it related to a problem?
  * Did you see this feature somewhere else?

* Bug Fix PR
  * Issue(s) fixed
  * What was done to fix it?

Looking for suggestions of templates or things in templates as well

**Comment by elreydetoda** [comment]
(I've had a bunch of these links saved for a while as "advanced" templating solutions, so just going to drop all the links I have here and hopefully it'll help)
 

While this probably isn't what we'd do, the @ansible-collections project has a bunch of files that we might be able to pull from: https://github.com/ansible-collections/.github

They also have all the other files we probably should have (i.e. SECURITY.md) and IIRC you can have multiple PR templates under the .github folder as well.

You can also link to different things if someone needs to submit feedback to a show, we could link them to the contact page: https://github.com/github/securitylab/blob/main/.github/ISSUE_TEMPLATE/config.yml

I think this one just had a really good design: https://github.com/linode/terraform-provider-linode/blob/main/.github/ISSUE_TEMPLATE/bug.yml

**Comment by CGBassPlayer** [comment]
These are great examples showing things I didn't even know about GitHub issue templates! I'll definitely be looking into this

**Comment by gerbrent** [comment]
This is so great both of you! I'll have a look aswell but see no reason why we can't implement some of these ideas.

My first hesitation with the otherwise amazing yaml example would be the downside of assigning rather rigid structure to our Issues when we've been using them in otherwise quite flexible ways - i.e. to track conversations and ideas that aren't strictly "bugs" or "feature requests". So, if there is a third option for flexibility that would be magnificent. Will check the repo and play a little, but on first blush this is fabulous! Thanks @CGBassPlayer ! 🎉

**Comment by CGBassPlayer** [comment]
> ...we've been using them in otherwise quite flexible ways - i.e. to track conversations and ideas that aren't strictly "bugs" or "feature requests". So, if there is a third option for flexibility that would be magnificent...

Well you are in luck @gerbrent! There is an option to create a blank issue at the bottom that will take you right to the usual new issue page. 
![Issue Selection](https://user-images.githubusercontent.com/34293941/188614667-9dd970a1-ef4d-4792-a482-ac6579dc4c4e.png)

I see these templates more as way to help new people figure out what they should put in a bug report or feature request rather than a strict structure we would have to stick to. I am also going to see if I can cheat a little bit and make a blank issue template if you think the blank issue could use more prominence in the issue type selection.

One thing I did notice with these new issue templates is that they are not yet implemented on the GitHub app, so those users will still also get a blank issue when they create one as well.

**Comment by gerbrent** [comment]
this is so great!

**Comment by CGBassPlayer** [comment]
@elreydetoda markdown is only data rendered while filling out the form for giving instructions, thanks, or anything you need to convey that doesn't need to be read on the ticket after. When you use the `textarea`, it works just like a markdown area in a blank issue. You can upload images, make lists, and do all the other markdown things.

**Comment by CGBassPlayer** [comment]
I thought the same thing at first as well. But once you click into it, you get the normal markdown view
![textarea](https://user-images.githubusercontent.com/34293941/188674384-cee832d8-fc1a-47d0-9b3c-26e0754693c7.png)

**Comment by CGBassPlayer** [comment]
So I am adding the the contributing checkbox for the templates. Is there any specific wording we want for this?

Also, do you guys think it would be good to have a development related template? Maybe to list the tools they are having an issue with and a normal summary to describe it? Kind of like this (most of this text is just stand in)
![dev issue template](https://user-images.githubusercontent.com/34293941/189118606-6489b7c6-dbc4-45bd-90bb-049d627523a9.png)

**Comment by gerbrent** [comment]
yes, that looks helpful!

I'm gonna wager Docker gets submitted first ; )

**Comment by gerbrent** [comment]
for specific wording: insert what you feel and we can always redact later..

**Comment by CGBassPlayer** [comment]
Is there any other ideas for templates we want before I mark this PR as ready?

**Comment by gerbrent** [comment]
I wonder if a "Episode metadata has errors" template might be helpful?
To cover the case where a listener notices a dead link, a typo, and incorrectly tagged guest, etc. for a specific episode.

**Comment by CGBassPlayer** [comment]
I like the idea. I can throw the show notes tag on those so we know it has to do with dead links. I'll add that now

**Comment by CGBassPlayer** [comment]
I can look into this. I am not sure why there was a large gap. Very strange to me.

But I can see how the checkbox being a task can get annoying. Did we want to remove it or try changing to something else?

**Comment by gerbrent** [comment]
On the submitted issue:
![image](https://user-images.githubusercontent.com/7018928/192841050-51f07cc1-5843-4544-b90e-9b20a46d4252.png)

On the issue template:
Notice there are THREE lines that suggest reading the Contributing Guidelines. Maybe a little superfluous...

![image](https://user-images.githubusercontent.com/7018928/192841655-8cecd000-4547-4e5e-8b68-9d260033a3e1.png)

**Comment by CGBassPlayer** [comment]
@gerbrent do you want the Contributing check removed completely? The bottom link will always be put there by GitHub so we don't necessarily need to put our own in the issue forms if we don't want it.

**Comment by gerbrent** [comment]
will test that! nice catch..

**Comment by CGBassPlayer** [comment]
@gerbrent 
> Notice there are THREE lines that suggest reading the Contributing Guidelines. Maybe a little superfluous...

> the "I have read through the Contributing Guidelines" section necessarily gets a check mark on every issue template submitted, however in the Issue post-submission, this is then "tracked" as a task. So, then, every single issue submitted will have a tracked, completed task associated with it.

Based on your concerns, are you thinking we should remove the contributing checkbox from the issue forms? We can put some text in that is only rendered while filling out the issue for them to review it.
