### ISSUE TITLE
E2E Tests - Slow Builds

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#394]
E2E Testing takes about 2m45 to build the test environment, including a hugo build, vm (container?) build, and package download/install. I'm sure we can think of ways of not needing to build the vm on every single E2E call, especially considering we have limited Actions minutes per month..

Thoughts? ideas?

Sample run:
https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/runs/8192069861?check_suite_focus=true

**Comment by gerbrent** [comment]
likely fixed by #353 🎉

**Comment by elreydetoda** [comment]
So, I shaved off about an average of 30 seconds but I don't think I'll be able to make it any faster.

I [enabled buildkit](https://github.com/elreydetoda/jupiterbroadcasting.com/commit/4d632606c314b62e3be33c847be8b1774cc2815a) for docker builds, and with that change you can see all the time it takes for [each step of the docker build](https://github.com/elreydetoda/jupiterbroadcasting.com/runs/8207282810).

From a quick glance the longest ones are:
- [hugo build](https://github.com/elreydetoda/jupiterbroadcasting.com/runs/8207282810#step:3:131) - can't really affect the speed of how fast this is without probably hosting our own runner...
- [pulling down the MSFT playwright container](https://github.com/elreydetoda/jupiterbroadcasting.com/runs/8207282810#step:3:221) - which we would've had a long time to install deps anyways (so this is probably faster)

The tests only take like [3 seconds to run](https://github.com/elreydetoda/jupiterbroadcasting.com/runs/8207282810#step:4:1) :sweat_smile:

**Comment by gerbrent** [comment]
....All that for 3 seconds?!!!? ; )

Nice work @elreydetoda , as always.
