### ISSUE TITLE
`Deploy to Prod` GH workflow - 5000+ lines of blank error?

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#398]
I'm seeing about 5000+ lines of blank errors in our [`Deploy to Production`](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/actions/workflows/deploy-prod.yml) GH action workflow. These don't seem to affect anything drastically or negatively, but.... what gives?

https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/runs/8232673539?check_suite_focus=true#step:4:23

![image](https://user-images.githubusercontent.com/7018928/188930040-e4458888-8362-4a5f-bbed-3891aabbdab6.png)

**Comment by gerbrent** [comment]
![image](https://user-images.githubusercontent.com/7018928/188930413-90cc3b37-b262-4cda-ac46-499c7d93c7ff.png)

**Comment by gerbrent** [comment]
![image](https://user-images.githubusercontent.com/7018928/188930560-442b24fc-9f5e-4311-b42b-6d620f011e25.png)


; )

**Comment by elreydetoda** [comment]
Looks like it's the marketplace action that [we're using](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/1ea70c453e09316d1f43d9a290e3735377f49518/.github/workflows/deploy-prod.yml#L36), they have an issue about it here: https://github.com/appleboy/ssh-action/issues/174

**Comment by CGBassPlayer** [comment]
It looks like since we use the master branch, the fix was applied and we are no longer seeing 5000 blank lines in the action being run.
![image](https://user-images.githubusercontent.com/34293941/236367945-fbd212e5-e216-473b-91a9-e239e8c342ff.png)
