### ISSUE TITLE
Wiki icon looks like a bar code

### ISSUE THREAD

**Issue by CGBassPlayer** [JupiterBroadcasting/jupiterbroadcasting.com#402]
![icons](https://user-images.githubusercontent.com/34293941/189122962-60fead34-012d-467f-b291-936fce6006a0.png)

The [`fa-wikidata`](https://forkaweso.me/Fork-Awesome/icon/wikidata/) icon looks more like a [`fa-barcode`](https://forkaweso.me/Fork-Awesome/icon/barcode/) than something like a wiki.

I propose that it should either be [`fa-wikipedia-w`](https://forkaweso.me/Fork-Awesome/icon/wikipedia-w) or [`fa-book`](https://forkaweso.me/Fork-Awesome/icon/book/)

**Comment by gerbrent** [comment]
... make it so!
