### ISSUE TITLE
Request: add matrix to social media buttons on each shows webpage

### ISSUE THREAD

**Issue by Ronkn** [JupiterBroadcasting/jupiterbroadcasting.com#403]
I noticed there are buttons for discord, Twitter, YouTube, etc, on each shows page. Perhaps it would be worth adding buttons for the associated matrix rooms to each shows web page as well?

Thanks

**Comment by gerbrent** [comment]
great idea! though there is value in linking to the greater community, since one can easily be oblivious to the other non-show offerings. Its a great discovery tool...

and I'm not convinced Matrix/Element does a good job of presenting these options..

**Comment by CGBassPlayer** [comment]
I am adding the matrix links for each show while I work on #402 if you want to throw me on this
