### ISSUE TITLE
Extras - show titles missing details

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#412]
Take Brunch w Tim Canham as an example.

On jb..com it appears as `87: Tim Canham` however should actually be - as is found on Fireside - `Brunch With Brent: Tim Canham`

## Fireside: 
https://extras.show/87

![image](https://user-images.githubusercontent.com/7018928/189255439-56b0116e-5e0d-41b5-acd2-1c489b55fefd.png)

## JB Episode page: 
https://www.jupiterbroadcasting.com/show/jupiter-extras/87/

![image](https://user-images.githubusercontent.com/7018928/189255595-9ced4e0e-6d0a-41bb-a8a7-43856b5391b2.png)

## JB Show Page - Extras: 
https://www.jupiterbroadcasting.com/show/jupiter-extras/

![image](https://user-images.githubusercontent.com/7018928/189255796-d6d69780-6792-4844-9305-ce3c7bf17844.png)

## JB Home Page: 
https://www.jupiterbroadcasting.com/page/4/

![image](https://user-images.githubusercontent.com/7018928/189255911-3d9e8f4b-c8ba-4b66-87dc-52e975d98083.png)

**Comment by gerbrent** [comment]
may relate to PR #81, Issue #67

**Comment by ChanceM** [comment]
The scraper splits on :

```python
    title = title.split(":", 1)[-1]
```

Simple check to see if there are numbers in the split or not would fix it.

**Comment by gerbrent** [comment]
nice one!

**Comment by gerbrent** [comment]
Would you be interested in implementing this one by @ChanceM ?

**Comment by ChanceM** [comment]
@gerbrent have a regex prepared, I'm going to test against a subset of titles and then I'll make a pull request for review.

**Comment by elreydetoda** [comment]
I didn't realize cross repo issues could close something like this...interesting...

So we still need to push all the titles with their corrected title names. These appear to be the affected shows: https://github.com/JupiterBroadcasting/show-scraper/pull/35#issuecomment-1246056641
