### ISSUE TITLE
Accessibility check

### ISSUE THREAD

**Issue by JR-git-hub** [JupiterBroadcasting/jupiterbroadcasting.com#414]
Check website for accessibility, log issues for follow-up/fix.

There are probably more comprehensive and potentially open source tests that can be run automatically or principled manual testing could also be done with screen readers, etc.

Here is an example automated test that found some easy to fix and most common issues:

https://accessibleweb.com/website-accessibility-checker/?page_url=https%3A%2F%2Fwww.jupiterbroadcasting.com

**Comment by ozcoder** [comment]
Also pa11y, Sa11y, WAVE, Axe, Accessibility Insights etc.
Maybe webhint too.

**Comment by gerbrent** [comment]
https://accessibleweb.com/website-accessibility-checker/?page_url=https%3A%2F%2Fwww.jupiterbroadcasting.com

![image](https://user-images.githubusercontent.com/7018928/189581117-24c04929-c560-4886-94ed-6bbd6c1e23f0.png)

**Comment by CGBassPlayer** [comment]
So I was looking into this a little bit and the only one I am not sure how to resolve would be the links back to the homepage. The report says `Links must have discernible text`, but the relative path to the home page is just `/` and therefore can't have any text in the link. Anyone have any thoughts on this?

**Comment by agbaraka** [comment]
Hi @CGBassPlayer.

I found the following solution from Stackoverflow.

https://stackoverflow.com/a/51715544/2813531

**Comment by CGBassPlayer** [comment]
> I found the following solution from Stackoverflow.

Thanks @agbaraka! I will look at this again later today
