### ISSUE TITLE
JBTitles.com, LUP End Show Song

### ISSUE THREAD

**Issue by optimusgray** [JupiterBroadcasting/jupiterbroadcasting.com#415]
Remove the "JBTitles.com" from the LUP end show song

**Comment by ChrisLAS** [comment]
Or perhaps we update jbtiles.com to point to the Matrix room?

Hmm!

**Comment by gerbrent** [comment]
@optimusgray Can you describe more of what you mean by "LUP end show song" ?

**Comment by gerbrent** [comment]
@optimusgray ? ^
