### ISSUE TITLE
Missing spacing around pagination on home page

### ISSUE THREAD

**Issue by MarcelRobitaille** [JupiterBroadcasting/jupiterbroadcasting.com#417]
To my eye, there should be more vertical spacing above and below the pagination on the homepage.

https://www.jupiterbroadcasting.com/
![image](https://user-images.githubusercontent.com/8503756/189732746-97151e61-23fc-4f7a-a769-1cea63b2d443.png)

Interestingly, there is spacing on a single show's page.

https://www.jupiterbroadcasting.com/show/coder-radio/
![image](https://user-images.githubusercontent.com/8503756/189733110-967e5b8b-0c8a-4678-9535-1ce2ac3c8908.png)

Reproduced on Firefox 104.0.1 and Chromium 104.0.5112.101. My viewport resolution (`window.innerWidth` and `window.innerHeight`) is 1680 x 904.

**Comment by CGBassPlayer** [comment]
Looks like we missing some padding! Thanks for the bug report. I will knock this out quick
