### ISSUE TITLE
Episode Page - move Sponsors above Episode Links in mobile view

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#430]
### URL

everywhere! ; ) All episode pages in mobile view

### On what type of device(s) did you see this bug?

Phone

### On which browser(s) are you seeing the problem?

Firefox

### Other Browser

Firefox' Responsive Design Mode

### Summary

On the Episode pages, it would be preferably to have the Sponsors section above the Episode Links section.

related to #400 

![image](https://user-images.githubusercontent.com/7018928/192628896-83045fbd-f7b2-4a5b-bf63-6219c41f19de.png)

### Contributing

- [X] I have read through the [Contributing Guidelines](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md)

**Comment by gerbrent** [comment]
@CGBassPlayer I know you were interested in this as a next step to #400. Wanna claim it?

**Comment by CGBassPlayer** [comment]
Sure! I'll keep looking into this

On an unrelated note, how was the issue form?

**Comment by gerbrent** [comment]
> On an unrelated note, how was the issue form?

good catch!

I'm feeling like us using it it a good test.. so it was fine! I Didn't have any issues and the flow was just fine. 💯

**Comment by CGBassPlayer** [comment]
Removing in progress tag for now as I have been super busy. I will hopefully get back to this at some point soon
