### ISSUE TITLE
Periodic matrix federation check

### ISSUE THREAD

**Issue by elreydetoda** [JupiterBroadcasting/jupiterbroadcasting.com#438]
> > Also might want to consider doing some type of periodic check on the federation tester 
>
> Was thinking the same! :brain: 

_Originally posted by @noblepayne in https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/381#issuecomment-1237531729_

I'm thinking we can just do a GH action or something to check this on a periodic basis. (Just creating this so we don't forget about it)

**Comment by CGBassPlayer** [comment]
My curiosity is peaked and I have a couple questions about this:
* Would this action check the contents or just if the files exists? 
* If the test fails, are their notifications set up or is that something we need to figure out?
* (A bit of a weird one) Would it make sense to make a python script in the `test` folder for the federation check and have an action call that script?

**Comment by elreydetoda** [comment]
> * Would this action check the contents or just if the files exists? 

So, #353 already does the server/client checks (#383/#420) from the JB website side. It tries to [request the well-known file](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/bb5fe8d042ffc415e79857c1c60f7c31a5d2e2b5/test/e2e/test_infra_configs.py#L16), and then it'll check to make sure the it' received a [2xx response](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/bb5fe8d042ffc415e79857c1c60f7c31a5d2e2b5/test/e2e/test_infra_configs.py#L18), the response actually [contains content](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/bb5fe8d042ffc415e79857c1c60f7c31a5d2e2b5/test/e2e/test_infra_configs.py#L19), and checks it against the expected [format of the data](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/bb5fe8d042ffc415e79857c1c60f7c31a5d2e2b5/test/e2e/test_infra_configs.py#L8-L13).

The only thing we're not doing (or won't be since it's not merged yet) is the federation check on a 3rd party server (like I'd mentioned [here](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/381#issuecomment-1235739227)):

> Also might want to consider doing some type of periodic check on the [federation tester API](https://federationtester.matrix.org/api/report?server_name=jupiterbroadcasting.com), but I don't know what a failure result from that would look like.

---

> * If the test fails, are their notifications set up or is that something we need to figure out?

Ya...this one becomes more difficult if we're doing it as a python script only :sweat_smile: . There might be something on the GH action marketplace that'll add functionality to handle this, but by default if we do it with a python script it's not going to have a notification method (unless we build it into it).

I'd wanted to do something like uptime kuma but I just did a quick test and it doesn't seem to want to respond in the way I was expecting. I think the `Body` field they have is only for [posts](https://github.com/louislam/uptime-kuma/issues/1107)...

I'm sure there are other more Operations oriented ways of doing this (i.e. [nagios](https://www.nagios.org/)), but if we're trying to keep this as light weight as possible then I think keeping it in GH actions makes sense.

---

> * (A bit of a weird one) Would it make sense to make a python script in the `test` folder for the federation check and have an action call that script?

Ya, we definitely could write a small python script/test to check if the [response's body](https://federationtester.matrix.org/api/report?server_name=jupiterbroadcasting.com) has `"FederationOK": true` and if it doesn't then the test would fail. While it could probably easily be done in the python requests library (which is what playwright uses under the hood IIRC), we could also easily do it in playwright (as shown [here](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/bb5fe8d042ffc415e79857c1c60f7c31a5d2e2b5/test/e2e/test_infra_configs.py#L20)) to check the contents of the response.

A way that we we could prevent running it in a normal PR (since the 3rd party site won't be affected till the actual deployment and so shouldn't sway a PR E2E testing scenario), is we can use what pytest calls [markers](https://docs.pytest.org/en/7.1.x/example/markers.html). We could create another custom marker (I've already added a [development marker](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/bb5fe8d042ffc415e79857c1c60f7c31a5d2e2b5/pytest.ini#L8), so you could more quickly iterate on your development) which could be something `periodic`. Then mark that test with it, after that you can specify when you run pytest something like `-k "not periodic"` (can't remember the exact syntax) and it'll run everything except periodic tests. Then we could have a separate GH action which could have `-k "periodic"` and it'll only run the periodic tests.

I'd honestly recommend we just make that a [default option](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/bb5fe8d042ffc415e79857c1c60f7c31a5d2e2b5/pytest.ini#L5) though (or with the [container args](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/bb5fe8d042ffc415e79857c1c60f7c31a5d2e2b5/Dockerfile.tests#L7)), now that I think about it because it'd be really annoying to have to specify that everytime... :sweat_smile:

**Comment by CGBassPlayer** [comment]
So my current plan is

* Have a periodic mark to flag all tests that would run on a schedule rather than on a PR
    ```ini
    markers =
        dev: "the current test(s) you're working on for developing"
        periodic: "tests that need to run on a schedule instead of running when a PR is made"
    ```

* Mimic the E2E action, but add the necessary arguments to prevent periodic tests not to be run during e2e tests and vice versa
    * E2E
    ```
    script -e -c "docker-compose exec testing pytest -m "not periodic" --base-url http://jb-com --junitxml report.xml"
    ```
    * Periodic
    ```
    script -e -c "docker-compose exec testing pytest -m periodic --base-url http://jb-com --junitxml report.xml"
    ```
Only real difference at this point is that I am not saving screenshots (didn't think it would really matter for tests against 3rd parties).

**Comment by elreydetoda** [comment]
Yep, that sounds perfect :partying_face: 

Reviewing your PR now :grin:
