### ISSUE TITLE
GH auto deleting branches (on jb.com's repo) after merge

### ISSUE THREAD

**Issue by elreydetoda** [JupiterBroadcasting/jupiterbroadcasting.com#453]
So the first time [this happened](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/433#issuecomment-1260151853) I thought "Maybe I just clicked the delete button on accident", but this time I'm positive I didn't click the delete button on #442.

I was going to click the delete button but it said I'd already deleted it and I didn't even get to see a delete button!

![image](https://user-images.githubusercontent.com/10230166/194720512-7868c4cb-c101-4494-889b-a1562140eccf.png)

So, I don't know for sure what is happening with the repo, but I think someone might have checked [this setting](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches), which'll auto delete branches after they're merged. Since we don't have [branch protection](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/433#issuecomment-1261827926) setup (to my knowledge), it's always going to delete any branch without branch protection on it (i.e. main right now since it's not default) because of that setting being enabled...

**Comment by gerbrent** [comment]
Confirming I've disabled `Automatically delete head branches` since, though it produces extra work to keep thing clean in the short term, it feels much safer until we can implement suitable Branch Protections.
