### ISSUE TITLE
Episode - browser page title to include show name

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#459]
### Feature Description

On Episode pages, the browser tab/window title does not include the Show name, only the Episode name in the form `Episode Name | Jupiter Broadcasting`

Would be more desirable to have the Show name and Episode number included aswell, such as:

`Episode Name` | `Show Name` `Episode number` | `Jupiter Broadcasting`

^ is the same formatting found on Episode cards throughout the website.
Note LAN likely is an exception to this titling, as was seen in #67 

---

### Current Show window title
![image](https://user-images.githubusercontent.com/7018928/195198045-4b9158d2-486a-4abf-9600-9e28888a45a1.png)

### Current Episode window title
![image](https://user-images.githubusercontent.com/7018928/195198124-723e47e6-5324-49be-a5ee-050b4b99694c.png)

### Current Episode Cards (reference for title formatting)
![image](https://user-images.githubusercontent.com/7018928/195198967-517967e4-bdde-4598-8564-424e3f32f06f.png)

### Contributing

- [X] I have read through the [Contributing Guidelines](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md)

**Comment by komish** [comment]
Hi folks!

Heard you were looking to participate in Hacktoberfest - thanks for doing that. I usually participate every year but had to miss last year. Looking to get back into it this year if my limited time allows for it. I'll grab this issue. PR to follow shortly. Happy to make any necessary changes.
