### ISSUE TITLE
Nav Menu: Enable opening of URL menu item as a new tab or window.

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#47]
Enable opening of URL menu item - for example, https://jupitergarage.com - as a new tab or window, similar to HTML behaviour `<a href="https://jupitergarage.com" target="_blank">`

A possible quick "hack", since Hugo doesn't seem to have this feature yet: 
* https://gist.github.com/dudil/edf2b1838c7cc5f1131a3777dbc662a9?permalink_comment_id=3795765#gistcomment-3795765

Hugo issue tickets discussing the feature request (never implemented):
* https://github.com/gohugoio/hugo/issues/3600
* https://github.com/jpescador/hugo-future-imperfect/issues/100

**Comment by StefanS-O** [comment]
you can now use the `identifier` in the config to specify if it should open in a new window.
If you use `ext-` as a prefix it will open in a new page. I did it for the Garage Sale:

`
[[Menu.Main]]
    name = "Garage Sale"
    identifier = "ext-garage-sale"
    url = "https://www.jupitergarage.com/"
    weight =60
`

**Comment by gerbrent** [comment]
amazing hack! Still can't believe this isn't built in...

Well done!
