### ISSUE TITLE
Contact - submit button hidden on missing field

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#485]
From a LUP listener, and will likely need more investigation:

> Btw the submit button is not reachable, when missing a mandatory field and the notification is shown, for me on mobile with my pixel7pro. Don't know if it's resolution related but I had to put in everything again to send it.

**Comment by CGBassPlayer** [comment]
Looks like the makers of the context form updated to use more native buttons and file pickers. This screenshot is from my iPhone X.

![contact form on iPhone X](https://user-images.githubusercontent.com/34293941/201545988-6aba5be1-655a-4176-844d-c3e322bcd215.png)

I was planning on figuring out how to add more browsers and/or resolutions with playwright after I finished my test expansion PR.

I will see if there is a way to update the iframe size for mobile vs desktop. But if not, we can just increase the height of the iframe.
