### ISSUE TITLE
Navigation creating 2 unnecessary 301s

### ISSUE THREAD

**Issue by kmogged** [JupiterBroadcasting/jupiterbroadcasting.com#489]
### URL

https://www.jupiterbroadcasting.com

### On what type of device(s) did you see this bug?

Desktop

### On which browser(s) are you seeing the problem?

Firefox

### Summary

The top navigation bar is forcing the browser to do 2x 301 hops to navigate to the page. This is bad for performance, but also one of the URLs in the chain is an http link, which could cause issues for some browsers today or in the near future.

To reproduce:
1. Open Dev console
2. Click on Network tab
3. Click on Boost! in the navigation at the top
4. You'll see the link points to https://www.jupiterbroadcasting.com/boost
5. When navigating to this link you are redirected to a **nonsecure** http://www.jupiterbroadcasting.com/boost/
6. This **nonsecure** URL upgrades and finally settles on https://www.jupiterbroadcasting.com/boost/

The URLs simply need to have that trailing slash added where it's missing.

**Comment by CGBassPlayer** [comment]
Just spit-balling here but I can think of 2 possible places that could cause this. 

1. Some Hugo configuration setting where the base url is setup
2. Some NGINX setting could be routing to the http and the force redirects is on by default.

I am not too knowledgeable in the the topic, but I can say that code itself uses relative links everywhere that does link to another site. So it has to be higher up the chain.

**Comment by gerbrent** [comment]
@ironicbadger, care to investigate w the help of @CGBassPlayer and @ChanceM ?

**Comment by noblepayne** [comment]
At least in the past, looks like [Hugo expects trailing slashes in some situations](https://github.com/gohugoio/hugo/issues/492#issuecomment-54968263).

Looking at the generated `sitemap.xml` perhaps supports this case:
```xml
<url>
<loc>https://www.jupiterbroadcasting.com/boost/</loc>
<lastmod>2022-07-03T03:35:01-05:00</lastmod>
</url>
```

Most of the other links on the page I've tried seem to already include the trailing slash (e.g episodes, pagination, etc). 

There's surely some web server trickier that could be done, but perhaps we just want to add trailing slashes to [all the hardcoded menu URLs in the config.toml](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/develop/config.toml#L111)?

**Comment by kmogged** [comment]
My only concern is if the site was ever served via object storage. S3 storage in AWS considers everything as a key and trailing slashes aren't allowed. Of course you can add a function to remove trailing slashes. Just that it puts us back into this redirect situation.

**Comment by gerbrent** [comment]
this is beginning to feel like all my experiences w rsync... trailing slashes matter!!

> add trailing slashes to all the hardcoded menu URLs in the config.toml

Seem like this is the simplest fix, or at least worth trying. If anyone would like to implement, please do so and PR for us to evaluate!

(and please indicate here that you'll work on it so we don't duplicate effort)

**Comment by kmogged** [comment]
Yes very much so, and technically slashes do work, but then you need to specify the index filename in your hosting. Not really unlike NGINX, httpd. Except web servers can have more elaborate rules for serving.

So:
/boost would be one object in S3
/boost/index.html would be another object in S3 and would serve as /boost/

This means if you want both to work your deployment would need to copy the "boost" object to both of those places at once.

I think simplest fix is to add these slashes! Worry about this other stuff when the time comes.

**Comment by ironicbadger** [comment]
My 2 cents...

Add the slashes and worry about objects when (IF!) we ever do it. No plans atm...

**Comment by kmogged** [comment]
I've never worked on Hugo, but I almost have this issue resolved. Not sure how to indicate I'm "working on this" in Github. I actually figured someone else would probably beat me to this.
