### ISSUE TITLE
Link Twitch in Community Tab and Live Page

### ISSUE THREAD

**Issue by reclaimingmytime** [JupiterBroadcasting/jupiterbroadcasting.com#496]
### Feature Description

I know Twitch isn't open source, but as Jupiter Broadcasting streams there, I think it makes sense to add it to the website so people that are used to this platform can use it. I agree PeerTube should be the primary platform, this is just an additional option.

I suggest a link to https://twitch.tv/jupiterbroadcasting can get added to the places where all social networks are listed, namely the Community drop-down in the header "Community" and the "Get Social" footer.

It could also be added to the stream URLs under the embedded PeerTube at https://www.jupiterbroadcasting.com/live/
<img width="626" alt="image" src="https://user-images.githubusercontent.com/35609464/214157399-40b722ec-cee5-4512-bf1e-847993258629.png">

### Reference to Feature

Twitch used to be embedded at https://www.jupiterbroadcasting.com/live/ before it got replaced by PeerTube.

**Comment by gerbrent** [comment]
great suggestion @reclaimingmytime !

**Comment by TheHesster** [comment]
I've gone ahead and added these in.
![TwitchSocial](https://user-images.githubusercontent.com/85858098/218327415-e6f6b09b-562b-45a6-b183-895c31e3aaa0.png)
![TwitchLocations](https://user-images.githubusercontent.com/85858098/218327421-c8c5457a-08ba-414f-9ab4-587c69e5efb9.png)

**Comment by elreydetoda** [comment]
Re-opening till the issue I identified (after merging 🤦) is fixed: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/506#pullrequestreview-1304835551
