### ISSUE TITLE
404 when accessing tags with a space

### ISSUE THREAD

**Issue by reclaimingmytime** [JupiterBroadcasting/jupiterbroadcasting.com#497]
### URL

https://www.jupiterbroadcasting.com/show/linux-unplugged/494/

### On what type of device(s) did you see this bug?

Phone, Desktop

### On which browser(s) are you seeing the problem?

Chrome

### Summary

When I access tags with multiple words, such as "jupiter broadcasting" or "remote desktop", I get redirected to a 404 page.
<img width="125" alt="image" src="https://user-images.githubusercontent.com/35609464/214371612-fee8708d-c1f2-494c-8bba-d9f725d0f548.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/35609464/214371567-78f87956-dbf1-4532-a8a6-6db2f96ff837.png">

Tags with one word redirect to the proper tags overview.

Maybe the issue is related to how a space is converted?

**Comment by gerbrent** [comment]
Nice catch.

Will add to this: 

* same behaviour with emoticon tags such as " 🦒 " as found in [LUP 489](https://www.jupiterbroadcasting.com/show/linux-unplugged/489/):

![image](https://user-images.githubusercontent.com/7018928/216793924-07164039-d914-4b2a-aec5-22dde033650e.png)

**Comment by gerbrent** [comment]
May be related: I also noticed the "Tags" url seems.... broken aswell. In my recollection, it used to present all tags ever present in alphabetical order, however now simply presents a "Tags" title w no content.

https://www.jupiterbroadcasting.com/tags/

**Comment by aliencloned** [comment]
This is happening for myself also on every show page. Just wanted to note I'm using Firefox.
