### ISSUE TITLE
Patreon listed only on LAN.com, nowhere else

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#5]
Patreon: 
    * listed on LAN.com, nowhere else.

**Comment by reclaimingmytime** [comment]
Again, you can just link to https://www.jupiterbroadcasting.com/support-us/ 😉

**Comment by gerbrent** [comment]
for reasons I'm not going to expand on here, we have challenges w Patreon that need solving, and are not simple. So... for now, not pushing Patreon, and the Memberships accomplish similar benefits for all.
