### ISSUE TITLE
"Tags" url/page present no content. Regression?

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#500]
> [...]the "Tags" url seems.... broken aswell. In my recollection, it used to present all tags ever present in alphabetical order, however now simply presents a "Tags" title w no content.

https://www.jupiterbroadcasting.com/tags/

_Originally posted by @gerbrent in https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/497#issuecomment-1416876932_

**Comment by CGBassPlayer** [comment]
Did this ever exist? I see we have a page where we pass in a tag and all the episodes related to it. But I don't see a tags page in our layout

**Comment by gerbrent** [comment]
I could swear I remember using this a couple times, but... no proof to offer.

It renders _something_, so hugo must be allowing it.
It certainly IS a desirable function, esp when combined w search.

**Comment by CGBassPlayer** [comment]
Oh I agree that it should be there. I just never used it and I wanted to make sure it actually existed from I go digging through the commits to see where it went.
