### ISSUE TITLE
Multiple Guest Entries for 1 Person

### ISSUE THREAD

**Issue by CGBassPlayer** [JupiterBroadcasting/jupiterbroadcasting.com#521]
### URL

https://www.jupiterbroadcasting.com/guests/page/2/
~https://www.jupiterbroadcasting.com/guests/page/4/~
https://www.jupiterbroadcasting.com/guests/page/6/

### On what type of device(s) did you see this bug?

Phone, Tablet, Desktop

### On which browser(s) are you seeing the problem?

Firefox, Chrome, Safari, Microsoft Edge

### Summary

I am noticing duplicate entries for guests on the show. These should probably be merged.

These are all the potentially duplicate guests I have seen:
- [cat](https://www.jupiterbroadcasting.com/guests/cat) and [catherine-kretzschmar](https://www.jupiterbroadcasting.com/guests/catherine-kretzschmar/)
- ~[heather](https://www.jupiterbroadcasting.com/guests/heather) and [heather-ellsworth](https://www.jupiterbroadcasting.com/guests/heather-ellsworth/)~
- [jeromelaban](https://www.jupiterbroadcasting.com/guests/jeromelaban) and [jlaban](https://www.jupiterbroadcasting.com/guests/jlaban)

**Comment by reclaimingmytime** [comment]
> [heather](https://www.jupiterbroadcasting.com/guests/heather) and [heather-ellsworth](https://www.jupiterbroadcasting.com/guests/heather-ellsworth/)

I don't think they're the same person 😄

Heather from SciByte and Heather from Canonical are two different people, as you can see from their Twitter profile.

https://mobile.twitter.com/scibyte_heather
https://mobile.twitter.com/linux_flower

Heater from SciByte's full name is Heather Rose.
https://web.archive.org/web/20150207022115/http://www.jupiterbroadcasting.com/hosts/

**Comment by CGBassPlayer** [comment]
Out of the 3, that set was the one I was least confident about

**Comment by 1701home** [comment]
I will work on this issue today and submit a new PR
