### ISSUE TITLE
Add Mastodon Links to Host and Show Profiles

### ISSUE THREAD

**Issue by BenjaminHCCarr** [JupiterBroadcasting/jupiterbroadcasting.com#525]
### Feature Description

It would be great to get Mastdon links added to the Social Media Bar for hosts:

Chris would be: https://podcastindex.social/@ChrisLAS
Alex would be: https://techhub.social/@ironicbadger

Couldn't make out what Michael would be on Coder Radio, went to the website to look it up, but no Mastodon Links

### Reference to Feature

Similar to #62 which added Social Media Links

**Comment by 1701home** [comment]
I have added the requested links.
[alex.md](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/files/10997497/alex.md)
[chris.md](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/files/10997502/chris.md)

**Comment by CGBassPlayer** [comment]
Adding this for whoever works on this 
Mike's Mastadon: https://podcastindex.social/@dominucco@mastodon.social
