### ISSUE TITLE
RSS Feed for All Audio has fallen out of date

### ISSUE THREAD

**Issue by allenkemp** [JupiterBroadcasting/jupiterbroadcasting.com#528]
### URL
https://feed.jupiter.zone/allshows

### On what type of device(s) did you see this bug?
Phone, Tablet, Desktop

### On which browser(s) are you seeing the problem?
Podcast apps utilizing rss feed for show discovery (downcast, overcast, etc..)

### Other Browser
No response

### Summary
No Jupiter shows after Linux Unplugged 501 are showing up in the allshows rss feed.  The individual show rss feeds seem to be fine.

**Comment by CGBassPlayer** [comment]
Update from matrix chat says @noblepayne is aware of it and is working on the fix.
