### ISSUE TITLE
Carousel to open episode on Fire Tab 7

### ISSUE THREAD

**Issue by Huckleberrysonne** [JupiterBroadcasting/jupiterbroadcasting.com#530]
### On what type of device(s) did you see this bug?

Tablet

### On which browser(s) are you seeing the problem?

Chrome

### Other Browser

Amazon Silk

### Summary

I see 1.5 of carousel icons in portrait view and click on the 0.5 icon which advances that icon to left justification instead of opening it as i expected.
when i click the 0.5 icon, i expect it to open. i must be clicking the advance arrow, so the icon advances instead of opens. i wanted it to open. when it advances to left justified, i am able to open it, but this is an extra step. i'd rather it opened when i clicked it the first time than have it advance where i have to click it again to open it.
this has something to do with the resolution of the Fire Tab 7
as discussed on matrix earlier today

**Comment by Huckleberrysonne** [comment]
cg_bassplayer
I went and looked it up and the fire tablet 7 is 600x1024. Looks like at that resolution in portrait mode, it is a little bit awkward. You can see half of the second show. But the site treats the carosuel as 1 show wide (because you can see 1 full show and half the other) so when you click the second show, it moves it over, but also click the link of the show at the same time, causing the carosuel to move over and then the second show page to load.
cg_bassplayer
I am starting to wonder if it because generally carosuels are images and aren't links to other pages, and carosuels generally have a feature where if you click an picture on it, it will move front and center. I am wondering if that is what is actually happening. It is moving that show image "front and center" while it is loading the next page. And since the site loads so fast, it just looks a little bit weird

**Comment by CGBassPlayer** [comment]
![image](https://user-images.githubusercontent.com/34293941/228721954-89f490db-c1a9-4795-a80e-08e49ab11723.png)
This is what the site looks like on at 600x1024 (The resolution of a Fire Tablet 7).

What is happening is when the user selects the show on the right carousel, it is moving the carousel so the "clicked" show moves to the primary while it is loading the page. This happens because at a width of 600px, only 1 show can be full displayed at a time, and considers all other shows to be (for a lack of better term) hidden off the screen. This also means the user (depending on caching) can see the carousel move before the show page is over, creating this awkward animation.

**Comment by Huckleberrysonne** [comment]
Hi! thanks for describing this. i don't know if this needs to be addressed, i wanted you guys to know about it.
it would be slick if you could either advance the carousel OR click the partial "off page" show open. i'm not sure if some 'fixes' would make this worse or more clunky. i'm not very tech saavy, so i'm replying to you.
thanks for your time, attention and expertise

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by CGBassPlayer** [comment]
Thanks for opening an issue about! I just wanted to make sure the problem was described as clearly as possible while we still remember what we talked about.

Not exactly sure what we are gonna do about this yet. But this issue will be updated as we go so you'll always be in the loop!

**Comment by Huckleberrysonne** [comment]
I was thinking about this more. I expected when i clicked a show, that show would open. I think intuitively, a tap should open the show, even when it's icon isn't 100% displayed. (there should be no advance/retard arrow?), instead a one finger swipe should advance or retard the carousel. carousel front and center, if that's a thing, should be de-emphasized as a condition of opening a show. i don't know if this right, just my thoughts

**Comment by CGBassPlayer** [comment]
The arrow exists for users with mouse and keyboard primarily and just was just never hidden when you get down to a table or mobile view. But the only part of the that advances the carousel is the arrow itself and it is only a box the size of the arrow itself. do tap anywhere but the blue highlight box in the screenshot below should bring you to that shows page.

![highlight of arrow](https://user-images.githubusercontent.com/34293941/229324807-79d67030-18cc-44ac-9af2-a9125850d050.png)

I also want to mention that the swipe function is there and you can swipe to the right to see the other shows on the carousel on smaller screens as well. In my testing on my iPhone X, I am able to tap on the sliver (screenshot below) of the show on the right even though the arrow this there so I never noticed this issue personally. 

![iPhone XR highlight of second show](https://user-images.githubusercontent.com/34293941/229325182-fca56ec2-de00-42ac-91e0-4f04f2c9f47e.png)

Like I vaguely mentioned on matrix when you initially brought this up, I think the library that gives us the ability to swipe the shows left and right is ended up moving the show you tapped (for a lack of better words) "into view" while it was trying to load the show page for you. I hope this is making sense for you @Huckleberrysonne as I want to make sure you understand what is going on and feel like you were well informed.

**Comment by Huckleberrysonne** [comment]
I remember now that the arrows are for non touchscreen navigation. i think the navigation isn't working the same on the fire tab 7. i think i am tapping well away from the arrow yet experiencing arrow functionality.
however, in any case, maybe it doesn't need to be addressed because i can't imagine the 2 GB fire tab will be used for navigating the internet because it's a pretty terrible experience and might get worse if navigation becomes more ram intensive in the future.
this device may be better suited for use on a LAN without much demand for intense ram use, maybe it's not ram where the problem is, but the same should be true if it's CPU, GPU or chipset computationally deficient.
if your device isn't having similar issues, perhaps this should be set aside and only be reference if relevant for some future issue.
thanks for your attention to this and your work on this project

**Comment by Huckleberrysonne** [comment]
thanks for working on this, to whom ever worked on it, i really appreciate it

Sent with [Proton Mail](https://proton.me/) secure email.
