### ISSUE TITLE
404 when accessing tags with an apostrophe (’)

### ISSUE THREAD

**Issue by CGBassPlayer** [JupiterBroadcasting/jupiterbroadcasting.com#534]
### URL

https://www.jupiterbroadcasting.com//tags/conan-o%E2%80%99brien-podcast/ ([OH 5](https://www.jupiterbroadcasting.com/show/office-hours/5/))
https://www.jupiterbroadcasting.com/tags/department-of-commerce%E2%80%99s-national-telecommunications-and-information-administration/ ([CODER 504](https://www.jupiterbroadcasting.com/show/coder-radio/504/))

### On what type of device(s) did you see this bug?

Phone, Tablet, Desktop

### On which browser(s) are you seeing the problem?

Firefox, Chrome, Safari, Microsoft Edge

### Summary

Similar issue to #497
While working on e2e testing. I noticed that the `conan o’brien podcast` tag from Office Hours 5 results in a 404. I am assuming this is from the apostrophe causing some kind of issue with generating the files possibly?

**Comment by reclaimingmytime** [comment]
This could also be related to issue #516.

**Comment by CGBassPlayer** [comment]
I think it is close. It seems like they both suffer from differing between the URL for the tag `\ud83e\udd92` vs :giraffe: and `conan-o%E2%80%99brien-podcast` vs `conan o’brien podcast`

**Comment by CGBassPlayer** [comment]
Update. I built the site locally and the tag page is `conan-obrien-podcast`... So that means that https://www.jupiterbroadcasting.com/tags/conan-obrien-podcast/ is the correct URL and hugo is removing apostrophes from tags when it builds the HTML files.
