### ISSUE TITLE
Office Hours - Pocket Office 1&2 missing

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#552]
### URL

https://www.jupiterbroadcasting.com/show/office-hours/

### Summary

Because of #550 we manually added LUP0523 #551 to the website. In the end, changes to Office Hours podcast feed (Chris does it again!) is responsible, and thus the fix: https://github.com/JupiterBroadcasting/show-scraper/pull/38

All that said: Office Hours Pocket Office [1](https://www.officehours.hair/p01) & [2](https://www.officehours.hair/p02) are still missing - of course!

So, figure we could use it to test the new fix to the scraper.

**Comment by gerbrent** [comment]
hmm! ok https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/actions/runs/5885691739/job/15962495801 was run by @noblepayne after merging https://github.com/JupiterBroadcasting/show-scraper/pull/38.

HOWEVER!

No Office Hours came in, likely due to the feed changes recently.

So.......... need to solve this new problem ; )

**Comment by CGBassPlayer** [comment]
Based on [this error message](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/actions/runs/5885684825/job/15962480921#step:6:174), I think it has to do with the fact that chris has added a `p` to the beginning of the episode. I believe the scraper uses that part of the URL to build the episode number based on [this code](https://github.com/JupiterBroadcasting/show-scraper/blob/4757105dcfd232a786fec7212c79b623dd04c3d9/scraper.py#L117-L118).

I think we can adjust this to make it work, still need to think it through first though

**Comment by CGBassPlayer** [comment]
Just throwing a note in here that this same issue is also affecting the test episode of Gamer Radio from back in December

**Comment by gerbrent** [comment]
for ref: https://coder.show/gamer

**Comment by gerbrent** [comment]
Leave it to JB to not follow any conventions in episode numbering ; )
Just keeping it interesting!!!

**Comment by ChanceM** [comment]
Guess I should have checked the issue log. JupiterBroadcasting/show-scraper#40 should close this one.
