### ISSUE TITLE
Periodic Tests Failing at Container Build

### ISSUE THREAD

**Issue by CGBassPlayer** [JupiterBroadcasting/jupiterbroadcasting.com#560]
The periodic tests are current failing to build using the `Pipfile.lock`.

Message from the failed action: [`ERROR: failed to solve: process "/bin/sh -c pipenv --bare sync --system" did not complete successfully: exit code: 1`](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/actions/runs/6064354094/job/16452715194#step:3:341)

**Comment by ChanceM** [comment]
I have a branch that rolls back and pins the working version, there seems to be a bug in the latest pipenv around editable packages.

**Comment by CGBassPlayer** [comment]
I think we should also look at getting the `playwright-pytest` plugin [v0.4.0](https://github.com/microsoft/playwright-pytest/releases/tag/v0.4.0) or higher into our testing soon too. I am not sure if playwright has picked it up yet (Didn't do the research yet).
