### ISSUE TITLE
Add Jupiter Station to RSS and Show Page

### ISSUE THREAD

**Issue by reclaimingmytime** [JupiterBroadcasting/jupiterbroadcasting.com#577]
### Feature Description

The Jupiter Station feed seems to be used for live stream notifications and highlights. Currently, it's not available on the website.

I think it makes sense to link Jupiter Station under "shows" and the RSS feed under "Shows --> RSS Feeds".

RSS: https://station.us-iad-1.linodeobjects.com/rss/station.xml
https://podverse.fm/podcast/Z3WCCOxYBB

**Comment by ChrisLAS** [comment]
Good catch, I also would like to see this.

I'll add one requirement, tho: Here at JB HQ, we need to set up DNS and put a friendly URL in front of that feed. Because we could likely move where that XML file lives in the near-ish future.

**Comment by ChrisLAS** [comment]
Ok, we have a much more user-friendly URL for the Jupiter Station RSS Feed now: Jupiter station.live.

So it would be fantastic to get that added to the site and point to that URL instead of the actual XML file.
