### ISSUE TITLE
Make Jupiter Station XML URL Great Again

### ISSUE THREAD

**Issue by ChrisLAS** [JupiterBroadcasting/jupiterbroadcasting.com#578]
### Feature Description

The Jupiter Station RSS url needs a DNS and direct in front of it. 

Currently, the URL is: https://station.us-iad-1.linodeobjects.com/rss/station.xml

We should consider setting up DNS, and a redirect for $DOMAIN/RSS go there. In case we want to move to another s3 provider or the like.

### Reference to Feature

https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/577

**Comment by reclaimingmytime** [comment]
There's already feed.jupiter.zone for feeds like for https://feed.jupiter.zone/allshows. That currently points to Feedburner, where you might be able to set up a proxy. https://www.reddit.com/r/podcasting/comments/1765tcr/feedburner_actually_works_with_podcasting_20/

**Comment by ChrisLAS** [comment]
Ok we are all set, jupiterstation.live points to the RSS feed for Jupiter Station now.
