### ISSUE TITLE
Calendar - embeded with the now unmaintained timezone detection library jstz

### ISSUE THREAD

**Issue by reclaimingmytime** [JupiterBroadcasting/jupiterbroadcasting.com#58]
Not sure if it's already in the works, but a dedicated calendar page similar to https://www.jupiterbroadcasting.com/release-calendar/ that adjusts to the user's time zone would be great.

Currently, the site is using a Google Calendar embed with the now unmaintained timezone detection library [jstz](https://github.com/iansinnott/jstz), so maybe we can find/build a more up-to-date self-hosted alternative.

**Comment by gerbrent** [comment]
good one!

so far we have: https://jupiterbroadcasting.net/calendar/ which so far mimics the current behaviour, though I'll leave the library specifics to those more all-knowing there.

**Comment by gerbrent** [comment]
also, thanks: we need to add it to the menu! #59

**Comment by reclaimingmytime** [comment]
Vanilla JavaScript supports timezone detection as well, so we might not even need an external library. https://stackoverflow.com/a/44935836

**Comment by gerbrent** [comment]
@reclaimingmytime Do you feel comfortable trying to sort this out?

**Comment by reclaimingmytime** [comment]
@gerbrent I don't think I have the necessary permissions to assign myself to this issue, but I can take a look at it ;)

@StefanS-O I see you [imported the calendar page](https://github.com/reclaimingmytime/jupiterbroadcasting.com/blob/3e39a04feba002c11009ce260629b3acec4cea46/themes/jb/layouts/calendar/single.html) in commit 3e39a04feba002c11009ce260629b3acec4cea46, but you didn't include the JavaScript that auto-detects the timezone or the dropdown to change the timezone manually. Is there a reason why you didn't include it?

I can try to rewrite the jQuery/jstz code from https://www.jupiterbroadcasting.com/release-calendar/ to vanilla JavaScript and include the functionality on the new website, if there's not a reason against that.

**Comment by StefanS-O** [comment]
@reclaimingmytime no just didn't know. I just copied the iframe code and that was it.
I could also integrate it like this: https://stackoverflow.com/questions/31821974/support-user-time-zone-in-embedded-google-calendar

**Comment by reclaimingmytime** [comment]
@StefanS-O All right. The stackoverflow link you sent uses _jstz_, which is no longer maintained.

I already have the code written using https://stackoverflow.com/questions/9772955/how-can-i-get-the-timezone-name-in-javascript/44935836#44935836 to auto-detect the timezone. I just wanted to make sure there wasn't a reason against implementing that feature.

I can create a pull request once it's ready to be merged.

**Comment by StefanS-O** [comment]
Yeah fine with me, did you understand how to add custom JS?

**Comment by reclaimingmytime** [comment]
Currently it's just a `<script>` tag on the page, should I included it in the `main.js` file or somewhere else?

**Comment by StefanS-O** [comment]
Maybe finish it up and then i will have a look :)

**Comment by StefanS-O** [comment]
Yep, it is ok to do it this way, because it is only needed on this page template. Otherwise it would have made sense to integrate it in the global JS.

**Comment by reclaimingmytime** [comment]
@StefanS-O Right, also, the extra JavaScript might slow down the loading time on every other page where it's not needed. Thanks!
