### ISSUE TITLE
Guests overflow into Sponsors

### ISSUE THREAD

**Issue by noblepayne** [JupiterBroadcasting/jupiterbroadcasting.com#585]
### URL

https://www.jupiterbroadcasting.com/show/linux-unplugged/554/

### On what type of device(s) did you see this bug?

Desktop

### On which browser(s) are you seeing the problem?

Chrome

### Summary

When there are many guests for an episode, the guest images do not wrap and instead extend to the sponsor section and are covered up by the sponsor entries. See attached image.

![image](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/assets/33278192/a48e91c3-06ce-400c-b905-4aa6c990b326)

**Comment by albertchae** [comment]
Hi, I noticed this issue while looking up show notes for https://www.jupiterbroadcasting.com/show/linux-unplugged/554/ and put up https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/588 which should fix it
