### ISSUE TITLE
Alex's Nix config link for nvidia broken in 119

### ISSUE THREAD

**Issue by ebdavison** [JupiterBroadcasting/jupiterbroadcasting.com#597]
### URL

https://selfhosted.show/119

### Type(s) of Problems

Broken Link

### Summary

This is the broken link: https://paste.ktz.cloud/vJ2jK93vmcM51Ad3S2lP3
Unknown where the correct link is due to the nature of pastebin

**Comment by reclaimingmytime** [comment]
> Unknown where the correct link is due to the nature of pastebin
The pastebin has a public unprotected "remove" button, so maybe someone pressed that.

**Comment by gerbrent** [comment]
@ironicbadger ?

**Comment by ironicbadger** [comment]
Fixed on the backend.

https://github.com/ironicbadger/nix-config/tree/main/testing

**Comment by ironicbadger** [comment]
#599

**Comment by CGBassPlayer** [comment]
> https://www.jupiterbroadcasting.com/show/self-hosted/119/ still shows the old pastebin link.
> 
> 
> 
> Maybe this needs to be adjusted manually.

The fix has not yet been deployed to the production site. Only the develop branch. I will get this fix onto the production site in a couple hours when I break from work.

**Comment by CGBassPlayer** [comment]
#600 Was just merged so the updated link should be on the site

**Comment by ebdavison** [comment]
thanks, all for the update
