### ISSUE TITLE
Calendar - typo: has the iCalendar standard, not RSS

### ISSUE THREAD

**Issue by reclaimingmytime** [JupiterBroadcasting/jupiterbroadcasting.com#61]
Just a small detail on the terminology.

https://jupiterbroadcasting.net/calendar/ says the following:
> Subscribe to The Calendar: [RSS](https://www.google.com/calendar/ical/jalb5frk4cunnaedbfemuqbhv4@group.calendar.google.com/public/basic.ics)

and provides a link to a `.ics` file. This standard is [iCalendar](https://en.wikipedia.org/wiki/ICalendar), not RSS.

**Comment by lodenrogue** [comment]
I can give this a shot

**Comment by lodenrogue** [comment]
PR: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/65

This seems to be the only place with that wording

**Comment by gerbrent** [comment]
thanks for your help @lodenrogue !
