### ISSUE TITLE
Coder 567 no description

### ISSUE THREAD

**Issue by ChrisLAS** [JupiterBroadcasting/jupiterbroadcasting.com#610]
### URL

https://www.jupiterbroadcasting.com/show/coder-radio/567/

### Type(s) of Problems

Other

### Summary

Coder was posted before the description was done, and thus, the JB.com version was built without a description. The post on Fireside has been updated with a description, and we need to update the post on the JB site.

**Comment by CGBassPlayer** [comment]
Reran the scraper manually got the description added. The content is now available

![Coder 567 screenshot](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/assets/34293941/3fa7b2cb-0a0d-4492-b410-13c1a7561634)
