### ISSUE TITLE
add links to JB GitHub repo, social media...

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#62]
... perhaps in footer.

**Comment by kbondarev** [comment]
I think it might be a good idea to add a bunch of social media icons with links like Instagram, telegram, matrix, GitHub, YouTube, etc.

Footer is a good idea, but also maybe somewhere at the top on the front page or the community page

**Comment by StefanS-O** [comment]
I think we should create it as the normal navigation in the config, so you can manage it there.
This also makes it easier to modify for the sub pages. we can have as many menus as we want and where to display them is decided in the template and can easily be moved.

**Comment by gerbrent** [comment]
> I think we should create it as the normal navigation in the config, so you can manage it there. This also makes it easier to modify for the sub pages. we can have as many menus as we want and where to display them is decided in the template and can easily be moved.

Great idea, since we should note: every Show has unique social media (ie. twitter profiles) thus simple modifications on a per-show basis is great.

**Comment by gerbrent** [comment]
closing as vague and mostly completed elsewhere.
