### ISSUE TITLE
Community page - add Telegram Group link

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#63]
requires #24

**Comment by elreydetoda** [comment]
Probably, but it doesn't hurt (from a community perspective) to still have it displayed. Similar to how the self-hosted show has their discord, for people that don't want to join matrix or enjoy discord more, it gets people interested in the network with the least amount of friction by just being able to hop in and chat.

**Comment by reesericci** [comment]
But it also fragments the community into seperate "channels" of discourse.
