### ISSUE TITLE
RSS Feeds does not work on mobile devices

### ISSUE THREAD

**Issue by py-crash** [JupiterBroadcasting/jupiterbroadcasting.com#677]
### URL

https://www.jupiterbroadcasting.com/

### On what type of device(s) did you see this bug?

Phone

### On which browser(s) are you seeing the problem?

Firefox, Chrome

### Summary

When I click the RSS-Feeds on a Mobile Device (Hamburger Menu > RSS Feeds) nothing happens. I tested on Firefox and Bromite (Chromoum fork) on mobile. 

Desktop site appears to work without a problem.

**Comment by CGBassPlayer** [comment]
Hey, thanks for reporting! This is actually a know bug where for some reason, the links to the feed link actually appear next to the RSS Feed menu item rather than. If you you tap on `RSS Feeds` and then swipe over, you can find the feeds.

**Comment by py-crash** [comment]
Thanks for the workaround
