### ISSUE TITLE
Menu - hiding behaviour: hide menu items less agressively

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#68]
Would be nice to adjust the menu hiding behaviour.

My experience:

## Full Screen:
Easy navigation, single click to get anywhere.

![image](https://user-images.githubusercontent.com/7018928/178122927-7f0d6981-8f56-45d8-a246-522dc6867d13.png)

## Half-Screen:
i.e. half of 1920x1080
Menu vanishes into hamburger despite plenty of real estate for *some* menu items.

![image](https://user-images.githubusercontent.com/7018928/178122993-89095045-c9de-442d-9cf0-9bbe10de453c.png)

## Current minimum width before menu items completely vanish:

![image](https://user-images.githubusercontent.com/7018928/178123022-0865e04f-63b8-4571-acad-afb1057008fb.png)

## Preferred Behaviour
To me would feel far more useful to hide menu items as they reach the right edge.
For example: "If a menu items become truncated by the right side of the page (i.e. the menu icon), then remove them from the main header and only include them in the hamburger menu. 

*All* items would appear in the hamburger menu, if the menu is present/needed, despite the above behaviour.

When the hamburger menu is in use, "Jupiter Broadcasting" link should also always appear on top left, to aid the user in going back to the home page, regardless of the browser width.

**Comment by Lord0fBytes** [comment]
I started looking into this a little. It looks like the nav menu we are using ([Bulma Navbar](https://bulma.io/documentation/components/navbar)) doesn't have a clean way of truncating the links like you are requesting. From what I understand there are two layouts for this Navbar; Desktop and Mobile. Basically what is happening is when you shrink the width of the browser to a certain point it goes into mobile layout (with the hamburger). It looks to be an on or off type of deal (again from what I understand). 

Part two of what you are asking for; `Jupiter Broadcasting` link can stay on the Navbar the entire time whether in desktop or mobile layout. I am pulling together a PR for this now. Should have something to submit by morning.

**Comment by kbondarev** [comment]
@Lord0fBytes, I have no idea if this would actually be helpful at all or not, but Bulma has [these helper classes](https://bulma.io/documentation/helpers/visibility-helpers/) to deal with different screen width.

**Comment by Lord0fBytes** [comment]
@kbondarev While that doesn't quite look like it will work the way we want; ironically it took me to somewhere where I did find some helpful information... the site's source code ;-P. 
Look like it can be done with some fairly simple (may regret saying that) javascripting that checks the width of the screen and hides elements.

**Comment by kbondarev** [comment]
@Lord0fBytes, no javascript required. These things are handled with CSS media queries. Or in this case just a single SASS variable to set for bulma, check the PR #107

Solution inspired by [this stackoverflow answer](https://stackoverflow.com/a/55654301)

**Comment by Lord0fBytes** [comment]
So this looks like it just adjusts the breakpoint toggle, but that still only makes it either desktop layout or mobile layout. 
I was trying to make it dynamically change the menu based on the width of the page. 
Here is a sample I mocked up to demonstrate what I was trying to accomplish. 
This is what I thought @gerbrent was originally looking for. 

Hopefully you can see from the gif that as the window shrinks the extra menu items get added to a 'more' menu. When it finally hits the break point it goes into mobile mode. 

https://user-images.githubusercontent.com/7501413/179359117-a8c74952-1cfd-40a9-b408-012787865b6d.MOV

**Comment by gerbrent** [comment]
Neat!

> This is what I thought @gerbrent was originally looking for.

I think it's worth investigating possible solutions, and I was hopefully just inspiring some creativity around this problem. Seems to have worked ; )

The unfortunate reality is that we will likely have *many* menu items, so a consistent, reliable method to make them user-friendly is the goal here. Open to all suggestions and opinions, certainly not just mine.

**Comment by kbondarev** [comment]
There’s also an options of having drop downs.
Maybe we should make “shows” drop down with a list of shows. Kinda like the current JB site. What do you think?

**Comment by gerbrent** [comment]
great idea, and see #88 for same (this topic should really be a separate ticket..)

**Comment by Lord0fBytes** [comment]
Ya I am working on the drop downs in 88. I was planning on doing 'Shows' and 'People'
