### ISSUE TITLE
scraper - make all episode.md filenames 4 digits, i.e. 0246.md

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#69]
Currently, files are sorted unnaturally (at least on GH, may be sorted differently locally depending on OS/file browser..), i.e. `248.md` before `25.md`

![image](https://user-images.githubusercontent.com/7018928/178129238-fdf9c97e-d790-43dd-9a8d-f111eaf77d8a.png)

This creates some long-term human discomfort in finding files within a directory. We typically think "the latest show is at the bottom!" but currently that is never the case.

I wonder if there is some intelligence/converting we can do to store all episodes in format `0000.md`, i.e. `0004.md`, `0024.md`, `0246.md` etc.

(also, rant: how is this style of unnatural sorting ever desired?)

**Comment by kbondarev** [comment]
100% agree with your rant :)
I wish file names would be treated differently for sorting by the OS if the prefix is just a number. That why you'd never have to pad it with zeros.

My initial reason for not padding the files with zeros, or putting the episode titles there, was for making the URL for the episodes simple.
But Hugo is awesome and I guess I cloud make it all work.

Leaving this here for reference:
https://gohugo.io/content-management/urls/
