### ISSUE TITLE
tags on Episode pages not dark mode

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#71]
![image](https://user-images.githubusercontent.com/7018928/178135651-c891c700-28ba-483a-909d-2a7df06a6efc.png)

**Comment by Lord0fBytes** [comment]
@gerbrent How does this look for the coloring? 
I used the variable color of `$grey-darker` for the background color. Something still seems off but I think it's the blue and that particular shade.  

<img width="997" alt="Screen Shot 2022-07-10 at 10 20 09 PM" src="https://user-images.githubusercontent.com/7501413/178176921-15db67af-ad3a-4186-9676-9b7350dfff38.png">

**Comment by gerbrent** [comment]
so much better! And your instinct is correct: that blue text is still problematic but this is great progress. I don't think the "I'm a link!" blue colour is necessary here, since it's rather intuitive that these are clickable items.

So, best case: this or close dark-gray shading, with more legible text (even white)

**Comment by Lord0fBytes** [comment]
I dont have permissions to assign this to myself, so I'll just comment that I am working on finishing this up. 
I should have a PR ready by tomorrow.
