### ISSUE TITLE
contributing.md - share project guidelines for how we work

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#82]
We've been receiving some great questions form folks just starting to join us in this project, and I feel they might be worth collecting at least in the form of an FAQ.

I'm happy to collect them w recommendations from you all.

**Comment by gerbrent** [comment]
> #1 priority is to hopefully avoid using anyone's time/effort - including you - on items that may eventually not be used. We want to spend time/effort on things that get implemented! So it's good practice to get consult first on an idea and the greater vision to make sure you can implement in the way that ends up best for all the moving pieces.

**Comment by kbondarev** [comment]
Maybe add that the frontend framework used is bulma and we should strive to use the CSS classes, components, etc. from there when possible rather than making custom CSS solutions

https://bulma.io/documentation/

**Comment by gerbrent** [comment]
... make it so @kbondarev !
I don't have the technical chops to write that cohesively, so will need to come from someone with more insight.

**Comment by gerbrent** [comment]
see [/CONTRIBUTING.md](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md)

(also, any GH shortcodes to reference repo files? )

**Comment by kbondarev** [comment]
I will do this over the weekend :)

**Comment by kbondarev** [comment]
@gerbrent Regards to shortcuts for file referencing, I don’t know any. In an issue I’d do the same as you did.
But inside markdown files you can use relative paths in the link

**Comment by kbondarev** [comment]
> I will do this over the weekend :)
@gerbrent 

Ended up putting this one to the last on my list today and it's a little too late now. This will be the next thing I'll tackle.

**Comment by kbondarev** [comment]
@gerbrent see #127  (sometimes I feel like I'm sending a [Wuphf](https://www.youtube.com/watch?v=pCTOZYPodyk) when I reference the issue in the PR and the PR in the issue)

- I cleaned up the doc a little. Kept the same Q&A format, but removed the quotes and made some bullet point answers instead. I think it a little more visually appealing and easier to follow.
- Added some emojis (wimpy kinda made me realizes that emojis make things a little more colorful :laughing: )
- Added a couple more questions and answers

What do you think? Is it good, anything missing I should add?

**Comment by gerbrent** [comment]
> a little more visually appealing and easier to follow. 
👍🏻 

> Added some emojis (wimpy kinda made me realizes that emojis make things a little more colorful laughing )
I'm just going to place this here.... https://gitmoji.dev/

Regarding the Q & A format - that was born out of purse laziness, haste, and conversation capture, but if we feel it's a nice approachable format I'm all for it.

**Comment by gerbrent** [comment]
Feedback on the content and layout changes:

Dear @kbondarev - I think I love you.
SUUUUUPER amazing additions and editing. Way better than I was envisioning/could have done myself. We are better for having you here!
