### ISSUE TITLE
scraper - latest Extras missing show artwork

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#83]
artwork missing on both main page card and episode page. Other episodes are ok.

![image](https://user-images.githubusercontent.com/7018928/178375064-3e17ab0b-4df5-4303-bf3e-c59b4b608e91.png)

![image](https://user-images.githubusercontent.com/7018928/178375132-7789e365-1a50-49c7-a308-98b139b51da9.png)

![image](https://user-images.githubusercontent.com/7018928/178375232-66ce6fb7-2efa-4be9-8de7-f5e583816da0.png)

**Comment by gerbrent** [comment]
Odd.

Now it seems the entire Extras Show page is missing the artwork, but seemingly nothing changed?

Just me?

![image](https://user-images.githubusercontent.com/7018928/178380662-8f76ac03-d985-4bb3-8513-5ea3b85793b0.png)

**Comment by gerbrent** [comment]
perhaps related to change in #85?

**Comment by kbondarev** [comment]
Oh shoot, I made a mess. I'll fix it right now.

**Comment by kbondarev** [comment]
It's kinda related to #76, I forgot to rename the header image and new episodes had different references to it. But also in #85 I changed all files to add the "slug" and change "episode_padded" params to have 4 digits, but for extras it also changed all the references to the header_image.
