### ISSUE TITLE
hosts - complete current hosts for each show, some hosts missing

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#86]
most shows have an incomplete list of hosts presented on Show page at present.

For example (not exhaustive list):
* LUP - missing Brent
* Coder - missing Wes (was the host in the back catalogue)
* Extras - missing many hosts

Could be best to refer to current JB website/subsites for correct hosts.
Or, better..... can we automate based on hosts scraped? 

input @kiro? @StefanS-O ?

**Comment by kbondarev** [comment]
It seems that for the show page (e.g. [lup](https://jupiterbroadcasting.net/show/linux-unplugged/)) it takes the hosts data from the `_index.md` file
My first instict was to, I agree with @gerbrent  and  automatically aggregate all the hosts that are listed in the episode files.

But then I realized the proper way to look at it is this:
- `hosts` in the _index.md are the **current hosts of the show**. For example Noah was a LUP host long time ago, but maybe it's exactly right to put him the top of the page there as the "host" of LUP
- `hosts` in each episode file are hosts specific in this episode

---

Maybe what we could do is have the title be something like "Current Hosts" and some interactive UI element to show "All current and past hosts". It could be a link/button or maybe 2 tabs. And by default we show the "Current Hosts", but we would also allow the visitor to switch the view to see all the hosts (including past ones)

In the background it would work like this:
- **Current Hosts**: the hosts that are set in the `_index.md` file of each show
- **All Hosts**: automatically aggregate all the hosts from all the episode file of the show

**Comment by kbondarev** [comment]
LUP has "retired hosts" section: https://linuxunplugged.com/hosts

**Comment by kbondarev** [comment]
I mentioned Noah, and looked around a little and realized that he's not in LUP hosts/guests at all. For example, he does host episode but not defined as one: https://linuxunplugged.com/112
We do have him on LAN as a guest: https://linuxactionnews.com/guests/kernellinux

Makes me think that maybe there are a lot of past episode that didn't define hosts/guests properly. Probably a separate issue tho

**Comment by gerbrent** [comment]
all of this is well thought-out and super valid points.

I love your idea of `Current Hosts` and `Past Hosts` - makes alot more sense from a weekly listener standpoint who might now be familiar w the back catalogue or the last decade of JB history.

**Comment by gerbrent** [comment]
Another option - let's call it the `Seperate Page Option`:

* Current hosts are featured top right of the Show page.
* Past hosts are featured in a subsection of the Show/Hosts page of each Show aswell as the JB/Hosts

To be clear - this problem does not exist for Guests as all guests are "past guests" at time of publish ; )

**Comment by gerbrent** [comment]
> Makes me think that maybe there are a lot of past episode that didn't define hosts/guests properly.

definitely an issue of past infrastructure/processes, but a very low priority issue......

**Comment by gerbrent** [comment]
sure! great suggestion. I will Make It So™.

**Comment by gerbrent** [comment]
An observation to help craft a solution here, possibly an automated one?
Using Brent as an example here, but surely applies to all profiles of Hosts/Guests

Observing that Brent...:
* ✅  listed as a host in Episodes pages - for instance, [LUP 467](https://jupiterbroadcasting.net/show/linux-unplugged/467/)
* ❌ *not* listed as a host at /LUP/hosts 
* ❌ does *not* have LUP listed in the "Shows with Brent" section (top right) in his [host profile](https://jupiterbroadcasting.net/hosts/brent/)
* ✅  does have the individual LUP episodes listed in his [host profile](https://jupiterbroadcasting.net/hosts/brent/)


Brent
![image](https://user-images.githubusercontent.com/7018928/180277263-299c1b6c-a23c-4983-abfc-95026a437f7a.png)

Possible solution principles:
* could implement some logic: if `host-on-episode` then list Show thumb on Host profile

**Comment by kbondarev** [comment]
I think this is the logic by which this operate at the moment:

- **Is person a host a specific episode?**
  - Is answered by the `hosts` param in each episode markdown file
  - Makes these true:
  

    > :white_check_mark:  listed as a host in Episodes pages - for instance, [LUP 467](https://jupiterbroadcasting.net/show/linux-unplugged/467/)
    
    > :white_check_mark: does have the individual LUP episodes listed in his [host profile](https://jupiterbroadcasting.net/hosts/brent/)

- **Is person a current host of a show?**
  - Is answered by the `hosts` param in `_index.md` files of each show
  - :point_up_2: In your case, @gerbrent, your username is missing in `_index.md` of LUP. And therefore, makes these not work:
    > :x: not listed as a host at /LUP/hosts
    > :x:  does not have LUP listed in the "Shows with Brent" section (top right) in his [host profile](https://jupiterbroadcasting.net/hosts/brent/)

**Comment by kbondarev** [comment]
This PR fixes it by modifying the `hosts` params in each `index.md`

If you want this logic to be implemented:
>if host-on-episode then list Show thumb on Host Profile
>if host-on-episode then list Person as Host on Show Page
rather than how things work right now (described above) - then it requires some actual coding, not just changing the content.

---

I think we the way things work right now, maybe the title "Shows with Brent Gervais" should be rather be "Brent Gervais is hosting these shows" or something similar with an **active** verb.

**Comment by gerbrent** [comment]
I think the way you implemented it here - i.e. explicitly - is mighty fine for now. 
Needing to intentionally change the listed hosts of a show is an acceptable implementation, and we can discuss the use case of a guest host at a later time.
