### ISSUE TITLE
menu - list Guests page in menu

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#88]
Currently no way to access a list of guests via navigation.

There is access to https://jupiterbroadcasting.net/guests/ if you know the URL.

**Comment by Lord0fBytes** [comment]
I am working on this issue currently.

**Comment by Lord0fBytes** [comment]
I just realized this was resolved in PR #100 
While working on this I was looking at a slightly different way of doing it. @gerbrent What do you think about the menu having child items?

![Screen Shot 2022-07-14 at 7 04 58 PM](https://user-images.githubusercontent.com/7501413/179115904-cba8c569-afb0-49b0-b3e6-7d11e14829ec.png)

People might not be the right wording, but it was a test. We could do the same for shows as well.

**Comment by gerbrent** [comment]
> I just realized this was resolved in PR https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/100

ahh, sorry I didn't catch that sooner. Still catching up here from quite the week.. (of travels)

I think a sub-menu us certainly an option for likely less-used pages such as "People", as you suggest. I'm hesitant to use it *too* often, however in your example above it's perfectly suited and a nice way to reduce the number of menu items. Nice!

**Comment by gerbrent** [comment]
And agree 100% - would be a great option for the "Shows" menu item. Yes please!

**Comment by gerbrent** [comment]
Also noting the white submenu colour - but I'm sure you noticed that already..... ; )

**Comment by Lord0fBytes** [comment]
> Also noting the white submenu colour - but I'm sure you noticed that already..... ; )

Yup lol. It was just a demo to explain what was in my head 😁
