### ISSUE TITLE
Hosts, Guests - different list pages for JB Home, Shows

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#91]
We likely require for both Hosts and Guests of shows:

* [x] JB Home menu to present link to i.e. https://jupiterbroadcasting.net/hosts for ALL Hosts and i.e. https://jupiterbroadcasting.net/guests for ALL Guests on the entire network.
* [ ] Show menu to present link to i.e. Show/hosts to present all hosts of this Show only. url could be https://jupiterbroadcasting.net/show/coder-radio/hosts
* [ ] Show menu to present link to i.e. Show/guests to present all guests of this Show only. url could be https://jupiterbroadcasting.net/show/coder-radio/guests

requires #89

**Comment by elreydetoda** [comment]
So, is the first listed task done, since they're listed under people in the menu?

![image](https://user-images.githubusercontent.com/10230166/179672034-9fb8918c-8b91-4169-acc2-0e6a7d7bb812.png)


So, a quick hacky way would be to leverage the logic of [this code](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/551e71a20d01b5fa9c8b87fd7d66dbc7613c116e/themes/jb/layouts/_default/list.html#L14) (from #100 I think), where it checks to see if it ends with `hosts`. I was able to just create a folder of `hosts` and then do a symlink inside that folder pointing to the `_index.md` file which is directly under the show (i.e. `show/coder-radio/hosts/_index.md` -> `show/coder-radio/_index.md`).

![image](https://user-images.githubusercontent.com/10230166/179680182-76b7e7d7-0e53-4d73-8d51-7a0d235df74a.png)

inside this folder: `content/show` I ran this:
```bash
for i in ./* ; do
  mkdir -p "${i}/hosts" && ln -s "$(realpath --relative-to="./${i}/hosts/" "${i}/_index.md")" "${i}/hosts/"
done
```

submitting a PR that's a WIP to get feedback on this solution.

**Comment by gerbrent** [comment]
@kbondarev - can you have a look and opinion on this approach?

**Comment by kbondarev** [comment]
@elreydetoda It's an interesting approach, however I'm not sure if it's what desired. The result of these symlinks is that the `show-name/hosts` URL path brings you to another "show-page" that doesn't have the episodes.
I think @gerbrent meant that it will be a page like this (same layout): https://jupiterbroadcasting.net/hosts/ but with the hosts there filtered to the specific show.

**Comment by kbondarev** [comment]
@elreydetoda oh I took a second look. I think I misunderstood what you meant at first.
So the symlinks would be there to only make hugo create those URLs, but then you'll have some logic in the theme files that looks at the path and would display something. Is that correct?

I'm don't know much about Hugo. But it does not seem a "Hugo" way to do it... Like you said "hacky". But I mean - if it works, it works.

**Comment by elreydetoda** [comment]
Ya, so the `show-name/hosts` isn't a symlink it's actually a folder (so it can use the default list.html page), and the symlink is just linking the _index.md file inside that to the one above it. Here is an image of what tree shows (just to kind of help visualize it):

![image](https://user-images.githubusercontent.com/10230166/179883773-54d1f8cb-fee7-4636-8e35-b29921e5a022.png)

So, the symlink is just to keep the information updated in the hosts subfolder of the show. It's also there so we can populate the `<show-name>/hosts` website URL as a list page (which re-uses the same template from the show's list page) `layouts/_default/list.html` 

You should also be able to pull down my PR (#121) and test it yourself @kbondarev , which might help with visualizing it. I've already made the change and was waiting to get feedback before I made it ready for merge.

**Comment by elreydetoda** [comment]
Awesome, thank you for the feedback @kbondarev! Ya, I was looking at the wrong page for what I was basing it off of :sweat_smile:, so this feedback really helps :bow: :slightly_smiling_face:

**Comment by Lord0fBytes** [comment]
Since you are working with host cards I should let you know in my upcoming PR there will be a new file called `small-readmore.html` which is the same as `small.html`, but it trucates the bio and adds a 'Read More' link to the host page. 
Shouldn't effect anything you are doing, but it might help to clean up the bios.

**Comment by elreydetoda** [comment]
Ya, @Lord0fBytes I'll probably do another PR if I get this one in before yours.

Alright, @gerbrent I think this (from what was being described) is what you're looking for (already pushed to my PR if you want to try it out)?

![image](https://user-images.githubusercontent.com/10230166/180601159-f0cbbd25-96ee-4d10-a99f-1ffb9dc1bdc5.png)

![image](https://user-images.githubusercontent.com/10230166/180601167-e039f85b-8a68-4606-a0e8-7af5ed941382.png)

![image](https://user-images.githubusercontent.com/10230166/180601206-1995ce50-94a5-4115-a429-024fabdf9b4b.png)

**Comment by gerbrent** [comment]
indeed! 

And also for guests too - task added to top comment since I wasn't explicit about that feature. Oops!

The hosts page here is moderately a duplicate in functionality, since hosts are listed on the Show and Episode pages currently, but guests filtered to a specific show appear nowhere and is the main functionality I was picturing too. 

Thanks for all this! Looking good,

**Comment by elreydetoda** [comment]
I don't know if I mentioned this ( I thought I did, but don't see a comment :sweat_smile: ) I'm waiting to do the guest part till after I do #110, because it'd be really hard to implement that functionality (filtering down to specific show for guests) with the way we use the `data/` folder now.

**Comment by kbondarev** [comment]
Removed blocked as that new structure for people (hosts/guests) and sponsors is merged

**Comment by elreydetoda** [comment]
Alright, I finished up the guest listing pages off of the show pages. Let me know if there's anything that should be changed :upside_down_face:  (if not let me know and I'll change the PR to ready to merge, BTW the PR has the most recent commits if you want to pull it down)

![image](https://user-images.githubusercontent.com/10230166/184345391-f1174d50-266c-4800-812e-d361ec399f23.png)

**Comment by gerbrent** [comment]
This looks great to me, I say PR-ready it!

**Comment by elreydetoda** [comment]
> This looks great to me, I say PR-ready it!

Cool 😁, it's ready now if someone wants to review/approve it: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/121
